/**
 * @file useRecommendHandlers.ts
 * @description AllTabEmpty에서 추출한 추천/개선 핸들러
 * - handleAPImprove: AP 최단거리 개선
 * - handleRecommendImprovement: 산업DB 기반 개선추천 (모달)
 * - autoRecommendO: 발생도(O) 자동추천
 */

import { useCallback, useState } from 'react';
import type { WorksheetState } from '../../../constants';
import type { ProcessedFMGroup } from '../processFailureLinks';
import type { RecommendCandidate } from '../RecommendImprovementModal';
import { applyAPImprovement } from './apMinCostMap';
import { calcAP, getMaxSeverity, getSafeSODValue } from '../riskOptUtils';
import { getAllPaths } from '../APImproveModal';
import { correctOccurrence } from './pcOccurrenceMap';
import { recommendOccurrence } from './occurrenceRecommendMap';
import { recommendDetection, D_SCORE_DESCRIPTION } from './detectionRatingMap';
import {
  type ScoredPCIndustry,
  type ScoredDCIndustry,
  findBestPcForSixStep,
  findBestDcForSixStep,
  computeOptimizedOccurrence,
  computeOptimizedDetection,
} from '../../../utils/optimizationOdIndustry';
import { autoFillMissingOccurrence } from '../../../utils/autoFillOccurrence';
import { autoFillMissingDetection } from '../../../utils/autoFillDetection';
import { PLACEHOLDER_NA, PLACEHOLDER_DASH, RECOMMEND_PREFIX } from '../allTabConstants';

interface UseRecommendHandlersParams {
  state: WorksheetState | undefined;
  setState: React.Dispatch<React.SetStateAction<WorksheetState>> | undefined;
  setDirty: React.Dispatch<React.SetStateAction<boolean>> | undefined;
  saveAtomicDB?: (force?: boolean) => void | Promise<void>;
  processedFMGroups: ProcessedFMGroup[];
  globalMaxSeverity: number;
}

/** 모달 상태 */
export interface RecommendModalState {
  isOpen: boolean;
  candidates: RecommendCandidate[];
  cftLeaderName: string;
  diagnostics?: {
    totalFMGroups: number;
    totalRows: number;
    sodMissingCount: number;
    apLCount: number;
  };
}

/** 자동생성값 판별 (덮어쓰기 가능): 빈값, "-", "N/A", "[추천]..." */
function isAutoGenerated(val: string): boolean {
  const v = (val || '').trim();
  return !v || v === PLACEHOLDER_DASH || v === PLACEHOLDER_NA || v.startsWith(RECOMMEND_PREFIX);
}

/** Import B5 PC 문자열 → §12 규칙 newO (산업DB 행 매칭 시 industry 우선) */
function newOFromPcText(currentO: number, pcText: string, scored: ScoredPCIndustry[]): number {
  const t = pcText.trim();
  const row = scored.find(
    s => s.method === t || t.includes(s.method) || s.method.includes(t),
  );
  if (row) return computeOptimizedOccurrence(currentO, row.industryO, row.keywordO);
  const co = correctOccurrence(pcText);
  const kwO = co.correctedO ?? recommendOccurrence(pcText);
  return computeOptimizedOccurrence(currentO, null, kwO && kwO > 0 ? kwO : null);
}

/** Import A6 DC 문자열 → §12 규칙 newD */
function newDFromDcText(currentD: number, dcText: string, scored: ScoredDCIndustry[]): number {
  const t = dcText.trim();
  const row = scored.find(
    s => s.method === t || t.includes(s.method) || s.method.includes(t),
  );
  if (row) return computeOptimizedDetection(currentD, row.industryD, row.keywordD);
  const kwD = recommendDetection(dcText);
  return computeOptimizedDetection(currentD, null, kwD > 0 ? kwD : null);
}

export function useRecommendHandlers({
  state, setState, setDirty, saveAtomicDB,
  processedFMGroups, globalMaxSeverity,
}: UseRecommendHandlersParams) {

  // ★ 개선추천 모달 상태
  const [recommendModal, setRecommendModal] = useState<RecommendModalState>({
    isOpen: false, candidates: [], cftLeaderName: '',
  });

  // ★ AP 최단거리 개선 핸들러
  const handleAPImprove = useCallback((targetLevel: 'L' | 'M') => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};

    const uniqueKeys: string[] = [];
    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (row.fcId && fmGroup.fmId) {
          uniqueKeys.push(`${fmGroup.fmId}-${row.fcId}`);
        }
      });
    });

    const { updatedData, stats } = applyAPImprovement(
      riskData, uniqueKeys, globalMaxSeverity, targetLevel,
    );

    if (stats.improved === 0 && stats.unreachable === 0) {
      alert(`개선 대상 없음: 모든 항목이 이미 ${targetLevel === 'L' ? 'L' : 'M 이하'} 등급입니다.`);
      return;
    }

    setState(prev => ({ ...prev, riskData: updatedData as Record<string, string | number> }));
    setDirty?.(true);

    const lines = [
      `[AP 최단거리 개선 완료]`,
      `S(심각도): ${globalMaxSeverity} (고정)`,
      `대상: ${stats.total}건`,
      `개선: ${stats.improved}건`,
    ];
    if (stats.hToL > 0) lines.push(`  H→L: ${stats.hToL}건`);
    if (stats.hToM > 0) lines.push(`  H→M: ${stats.hToM}건`);
    if (stats.mToL > 0) lines.push(`  M→L: ${stats.mToL}건`);
    if (stats.unreachable > 0) lines.push(`개선불가(O=2,D=2에서도 L 미달): ${stats.unreachable}건`);
    lines.push('', '※ O, D 값이 최소 cost로 자동보정되었습니다.');
    lines.push('※ 저장 버튼을 눌러 DB에 반영하세요.');
    alert(lines.join('\n'));
  }, [state, setState, setDirty, processedFMGroups, globalMaxSeverity]);

  // ★ 개선추천 — 모달 열기 (데이터 준비 + 모달 표시)
  const handleRecommendImprovement = useCallback(async () => {
    if (!state || !setState) {
      console.info('[Recommend] state/setState 미준비 — 모달 열기 스킵');
      return;
    }
    if (processedFMGroups.length === 0) {
      alert('고장연결 데이터가 없습니다. 4단계 고장연결을 먼저 완료해주세요.');
      return;
    }

    try {
    const riskData = state.riskData || {};

    // CFT 리더(FMEA 책임자) 이름 가져오기
    let cftLeaderName = '';
    try {
      const fmeaId = state?.fmeaId || new URLSearchParams(window.location.search).get('id') || '';
      if (fmeaId) {
        const infoRes = await fetch(`/api/fmea/info?fmeaId=${encodeURIComponent(fmeaId)}`);
        const infoData = await infoRes.json();
        cftLeaderName = infoData?.fmeaInfo?.responsible || infoData?.fmeaInfo?.fmeaResponsibleName || '';
      }
    } catch (err) { console.error('[Recommend] CFT 리더 조회 실패:', err); }

    // ★ 산업DB + Import B5/A6 병렬 로드
    let scoredPCs: ScoredPCIndustry[] = [];
    let scoredDCs: ScoredDCIndustry[] = [];
    // Import B5(PC)/A6(DC) 직접매칭용 맵
    const fcToPcMap = new Map<string, string[]>();
    const fcToDcMap = new Map<string, string[]>();
    try {
      const fmeaId = state?.fmeaId || new URLSearchParams(window.location.search).get('id') || '';
      const [krPcRes, krDcRes, masterRes] = await Promise.all([
        fetch('/api/kr-industry?type=prevention').then(r => r.json()).catch(() => ({ prevention: [] })),
        fetch('/api/kr-industry?type=detection').then(r => r.json()).catch(() => ({ detection: [] })),
        fmeaId ? fetch(`/api/pfmea/master?fmeaId=${fmeaId}&includeItems=true`, { cache: 'no-store' }).then(r => r.json()).catch(() => null) : Promise.resolve(null),
      ]);
      scoredPCs = ((krPcRes.prevention || []) as { method: string; defaultRating?: number | null }[])
        .filter(e => e.method)
        .map(e => {
          const co = correctOccurrence(e.method);
          const rec = recommendOccurrence(e.method);
          const keywordO =
            co.correctedO != null && co.correctedO > 0
              ? co.correctedO
              : rec != null && rec > 0
                ? rec
                : null;
          const dr = e.defaultRating;
          const industryO =
            dr != null && dr >= 1 && dr <= 10 ? Math.round(dr) : null;
          return { method: e.method, industryO, keywordO };
        });
      scoredDCs = ((krDcRes.detection || []) as {
        method: string;
        methodType?: string;
        defaultRating?: number | null;
      }[])
        .filter(e => e.method)
        .filter(e => {
          const m = (e.methodType || '').trim();
          return !m || m === '자동';
        })
        .map(e => {
          const rd = recommendDetection(e.method);
          const dr = e.defaultRating;
          const industryD =
            dr != null && dr >= 1 && dr <= 10 ? Math.round(dr) : null;
          return {
            method: e.method,
            industryD,
            keywordD: rd > 0 ? rd : null,
          };
        });
      // ★ Import FC↔PC/DC 직접매칭 맵 구축 (B5/A6)
      if (masterRes?.dataset?.failureChains) {
        for (const ch of masterRes.dataset.failureChains as Array<{ processNo?: string; fcValue?: string; pcValue?: string; dcValue?: string }>) {
          const fc = (ch.fcValue || '').trim();
          const pNo = (ch.processNo || '').trim();
          const pc = (ch.pcValue || '').trim().replace(/^P:/, '').trim();
          const dc = (ch.dcValue || '').trim().replace(/^D:/, '').trim();
          if (fc && pc) {
            const key = `${pNo}|${fc}`;
            const list = fcToPcMap.get(key) || [];
            if (!list.includes(pc)) list.push(pc);
            fcToPcMap.set(key, list);
          }
          if (fc && dc) {
            const key = `${pNo}|${fc}`;
            const list = fcToDcMap.get(key) || [];
            if (!list.includes(dc)) list.push(dc);
            fcToDcMap.set(key, list);
          }
        }
      }
    } catch (err) { console.error('[Recommend] 데이터 로드 실패:', err); }

    // H/M 항목 수집 + 추천안 사전 계산 (산업DB + Import 직접매칭 병합)
    const candidates: RecommendCandidate[] = [];
    // ★ 진단 카운터
    let totalRows = 0;
    let sodMissingCount = 0;
    let apLCount = 0;

    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (!row.fcId || !fmGroup.fmId) return;
        totalRows++;
        const uk = `${fmGroup.fmId}-${row.fcId}`;
        const s = getSafeSODValue(riskData, `risk-${uk}-S`) || getMaxSeverity(fmGroup.fmId, state);
        const o = getSafeSODValue(riskData, `risk-${uk}-O`);
        const d = getSafeSODValue(riskData, `risk-${uk}-D`);
        const sodComplete = s > 0 && o > 0 && d > 0;
        if (!sodComplete) sodMissingCount++;
        const ap: 'H' | 'M' | 'L' = sodComplete ? (calcAP(s, o, d) || 'L') : 'L';
        if (sodComplete && ap !== 'H' && ap !== 'M') apLCount++;

        const prevOptKey = `prevention-opt-${uk}`;
        const detOptKey = `detection-opt-${uk}`;
        const curPrevOpt = ((riskData[prevOptKey] as string) || '').trim();
        const curDetOpt = ((riskData[detOptKey] as string) || '').trim();
        const hasPrev = !isAutoGenerated(curPrevOpt);
        const hasDet = !isAutoGenerated(curDetOpt);

        // 5단계 현재 예방관리(PC)/검출관리(DC) 텍스트
        const curPrevText = ((riskData[`prevention-${uk}`] as string) || '').trim();
        const curDetText = ((riskData[`detection-${uk}`] as string) || '').trim();

        // ★ Import 직접매칭 우선 확인 (B5→PC, A6→DC)
        const processNo = (fmGroup.fmProcessNo || '').trim();
        const fcText = (row.fcText || '').trim();
        const directKey = `${processNo}|${fcText}`;
        const directPcList = fcToPcMap.get(directKey);
        const directDcList = fcToDcMap.get(directKey);

        // 추천안 사전 계산 — SOD 있을 때 AP경로, 없어도 Import 직접매칭은 항상 표시
        let prevRecommend = '';
        let detRecommend = '';

        /** 모달 목표 O/D — §12 산출값이 있으면 AP 경로 목표 대신 표시 */
        let suggestedTargetO: number | null = null;
        let suggestedTargetD: number | null = null;

        if (sodComplete) {
          // SOD 완비 → AP경로 기반 추천
          const paths = getAllPaths(s, o, d);
          const effectiveRec = paths.oOnly.feasible ? 'O_ONLY' as const
            : paths.dOnly.feasible ? 'D_ONLY' as const
            : paths.both.feasible ? 'BOTH' as const
            : undefined;

          if (!hasPrev) {
            // Import PC 직접매칭 우선
            if (directPcList && directPcList.length > 0) {
              const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly
                : effectiveRec === 'D_ONLY' ? paths.dOnly
                  : effectiveRec === 'BOTH' ? paths.both
                    : null;
              const needsO = effectiveRec === 'O_ONLY' || effectiveRec === 'BOTH';
              if (pathData && needsO) {
                const neo = newOFromPcText(o, directPcList[0], scoredPCs);
                const showO = Math.min(neo, pathData.targetO);
                suggestedTargetO = showO;
                prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${showO} ${directPcList[0]}`;
              } else {
                prevRecommend = `${RECOMMEND_PREFIX} ${directPcList[0]}`;
              }
            } else if (effectiveRec) {
              const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly : effectiveRec === 'D_ONLY' ? paths.dOnly : paths.both;
              const needsO = effectiveRec === 'O_ONLY' || effectiveRec === 'BOTH';
              if (needsO) {
                const best = findBestPcForSixStep(o, scoredPCs, pathData.targetO);
                if (best) {
                  suggestedTargetO = best.newO;
                  prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${best.newO} ${best.method}`;
                } else {
                  prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${pathData.targetO} 개선 필요`;
                }
              } else {
                prevRecommend = PLACEHOLDER_NA;
              }
            }
          }

          if (!hasDet) {
            // Import DC 직접매칭 우선 (PC와 동일 우선순위)
            if (directDcList && directDcList.length > 0) {
              const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly
                : effectiveRec === 'D_ONLY' ? paths.dOnly
                  : effectiveRec === 'BOTH' ? paths.both
                    : null;
              const needsD = effectiveRec === 'D_ONLY' || effectiveRec === 'BOTH';
              if (pathData && needsD) {
                const nd = newDFromDcText(d, directDcList[0], scoredDCs);
                const showD = Math.min(nd, pathData.targetD);
                suggestedTargetD = showD;
                detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${showD} ${directDcList[0]}`;
              } else {
                detRecommend = `${RECOMMEND_PREFIX} ${directDcList[0]}`;
              }
            } else if (effectiveRec) {
              const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly : effectiveRec === 'D_ONLY' ? paths.dOnly : paths.both;
              const needsD = effectiveRec === 'D_ONLY' || effectiveRec === 'BOTH';
              if (needsD) {
                const best = findBestDcForSixStep(d, scoredDCs, pathData.targetD);
                if (best) {
                  suggestedTargetD = best.newD;
                  detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${best.newD} ${best.method}`;
                } else {
                  detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${pathData.targetD} 개선 필요`;
                }
              } else {
                detRecommend = PLACEHOLDER_NA;
              }
            }
          }
        } else {
          // SOD 미입력 → Import 직접매칭만 표시
          if (!hasPrev && directPcList && directPcList.length > 0) {
            prevRecommend = `${RECOMMEND_PREFIX} ${directPcList[0]}`;
          }
          if (!hasDet && directDcList && directDcList.length > 0) {
            const importD = recommendDetection(directDcList[0]);
            const dDesc = importD > 0 ? D_SCORE_DESCRIPTION[importD] : null;
            detRecommend = dDesc ? `${RECOMMEND_PREFIX} ${dDesc}` : `${RECOMMEND_PREFIX} ${directDcList[0]}`;
          }
        }

        // 목표 O'/D' 계산 (AP'=L 달성 기준) + §12 산출 목표 병합
        let targetO = o;
        let targetD = d;
        let targetAP: 'H' | 'M' | 'L' = 'L';
        if (sodComplete) {
          const paths = getAllPaths(s, o, d);
          const pathData = paths.oOnly.feasible ? paths.oOnly
            : paths.dOnly.feasible ? paths.dOnly
            : paths.both.feasible ? paths.both
            : null;
          targetO = pathData ? pathData.targetO : o;
          targetD = pathData ? pathData.targetD : d;
          if (suggestedTargetO !== null) targetO = suggestedTargetO;
          if (suggestedTargetD !== null) targetD = suggestedTargetD;
          targetAP = calcAP(s, targetO, targetD) || 'L';
        }

        candidates.push({
          uniqueKey: uk,
          fmId: fmGroup.fmId,
          fcId: row.fcId,
          processNo: fmGroup.fmProcessNo,
          processName: fmGroup.fmProcessName,
          fmText: fmGroup.fmText,
          fcText: row.fcText,
          s, o, d, ap,
          hasPrev, hasDet,
          prevRecommend, detRecommend,
          curPrevText, curDetText,
          curPrevOpt, curDetOpt,
          targetO, targetD, targetAP,
        });
      });
    });

    // 모달 열기 (진단 정보 포함)
    setRecommendModal({
      isOpen: true, candidates, cftLeaderName,
      diagnostics: {
        totalFMGroups: processedFMGroups.length,
        totalRows,
        sodMissingCount,
        apLCount,
      },
    });
    } catch (err) { console.error('[Recommend] 추천 처리 실패:', err); }
  }, [state, setState, processedFMGroups]);

  // ★ 선택적용 핸들러 (모달에서 호출) — checkedKeys로 체크된 행만 적용
  const applyRecommendations = useCallback((options: { prevention: boolean; detection: boolean; checkedKeys?: Set<string> }) => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};
    const { candidates, cftLeaderName } = recommendModal;
    const updates: Record<string, string> = {};
    let count = 0;
    const checkedKeys = options.checkedKeys;

    candidates.forEach(c => {
      const uk = c.uniqueKey;
      // 체크된 행만 적용 (checkedKeys가 없으면 전체 적용 — 호환성)
      if (checkedKeys && !checkedKeys.has(uk)) return;

      const prevKey = `prevention-opt-${uk}`;
      const detKey = `detection-opt-${uk}`;
      const personKey = `person-opt-${uk}`;

      if (options.prevention && !c.hasPrev && c.prevRecommend && c.prevRecommend !== PLACEHOLDER_NA) {
        updates[prevKey] = c.prevRecommend;
      }
      if (options.detection && !c.hasDet && c.detRecommend && c.detRecommend !== PLACEHOLDER_NA) {
        updates[detKey] = c.detRecommend;
      }

      // ★ N/A 마커 (결과 기반): 한쪽에만 추천 적용 → 반대쪽이 자동생성값이면 N/A 표시
      const wroteRealPrev = !!updates[prevKey] && updates[prevKey] !== PLACEHOLDER_NA;
      const wroteRealDet = !!updates[detKey] && updates[detKey] !== PLACEHOLDER_NA;
      if (wroteRealPrev && !wroteRealDet && !c.hasDet && isAutoGenerated((riskData[detKey] as string) || '')) {
        updates[detKey] = PLACEHOLDER_NA;
      }
      if (wroteRealDet && !wroteRealPrev && !c.hasPrev && isAutoGenerated((riskData[prevKey] as string) || '')) {
        updates[prevKey] = PLACEHOLDER_NA;
      }

      // 책임자 자동 배정
      if (cftLeaderName && (updates[prevKey] || updates[detKey])) {
        if (!((riskData[personKey] as string) || '').trim()) {
          updates[personKey] = cftLeaderName;
        }
      }

      if (updates[prevKey] || updates[detKey]) count++;
    });

    if (Object.keys(updates).length === 0) return;

    setState(prev => ({ ...prev, riskData: { ...(prev.riskData || {}), ...updates } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [state, setState, setDirty, saveAtomicDB, recommendModal]);

  // ★ 개별 항목 적용 핸들러 (IndustryImproveModal에서 호출)
  const applySingleRecommendation = useCallback((
    uniqueKey: string, mode: 'prevention' | 'detection', value: string,
  ) => {
    if (!setState) return;
    const key = mode === 'prevention' ? `prevention-opt-${uniqueKey}` : `detection-opt-${uniqueKey}`;
    setState(prev => ({
      ...prev,
      riskData: { ...(prev.riskData || {}), [key]: value },
    }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [setState, setDirty, saveAtomicDB]);

  // ★ 모달 닫기
  const closeRecommendModal = useCallback(() => {
    setRecommendModal(prev => ({ ...prev, isOpen: false }));
  }, []);

  // ★ 발생도(O) 자동추천 — PC 텍스트 기반
  const autoRecommendO = useCallback(() => {
    if (!state?.riskData || !setState) return;
    const fls = (state.failureLinks || []).map((fl) => ({
      fmId: String(fl.fmId || ''),
      fcId: String(fl.fcId || ''),
    }));
    const result = autoFillMissingOccurrence(state.riskData || {}, fls);
    if (result.filledCount === 0) {
      alert('발생도(O) 누락이 없습니다.');
      return;
    }
    setState((prev: WorksheetState) => ({ ...prev, riskData: result.updatedRiskData as { [key: string]: string | number } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
    alert(`발생도(O) ${result.filledCount}건 자동추천 완료\n\n${result.details.slice(0, 5).map(d => `• ${d.reason}`).join('\n')}${result.details.length > 5 ? `\n... 외 ${result.details.length - 5}건` : ''}`);
  }, [state?.riskData, state?.failureLinks, setState, setDirty, saveAtomicDB]);

  // ★ 검출도(D) 자동추천 — DC 텍스트 기반 AIAG-VDA 키워드 매칭
  const autoRecommendD = useCallback(() => {
    if (!state?.riskData || !setState) return;
    const fls = (state.failureLinks || []).map((fl) => ({
      fmId: String(fl.fmId || ''),
      fcId: String(fl.fcId || ''),
    }));
    const result = autoFillMissingDetection(state.riskData || {}, fls);
    if (result.filledCount === 0) {
      alert('검출도(D) 누락이 없습니다.');
      return;
    }
    setState((prev: WorksheetState) => ({ ...prev, riskData: result.updatedRiskData as { [key: string]: string | number } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
    alert(`검출도(D) ${result.filledCount}건 자동추천 완료\n\n${result.details.slice(0, 5).map(d => `• ${d.reason}`).join('\n')}${result.details.length > 5 ? `\n... 외 ${result.details.length - 5}건` : ''}`);
  }, [state?.riskData, state?.failureLinks, setState, setDirty, saveAtomicDB]);

  return {
    handleAPImprove,
    handleRecommendImprovement,
    autoRecommendO,
    autoRecommendD,
    // ★ 모달 관련
    recommendModal,
    closeRecommendModal,
    applyRecommendations,
    applySingleRecommendation,
  };
}
