/**
 * @file useRecommendHandlers.ts
 * @description AllTabEmpty에서 추출한 추천/개선 핸들러
 * - handleAPImprove: AP 최단거리 개선
 * - handleRecommendImprovement: 산업DB 기반 개선추천 (모달)
 * - autoRecommendO: 발생도(O) 자동추천
 */

import { useCallback, useState } from 'react';
import type { WorksheetState } from '../../../constants';
import type { ProcessedFMGroup } from '../processFailureLinks';
import type { RecommendCandidate } from '../RecommendImprovementModal';
import { applyAPImprovement } from './apMinCostMap';
import { calcAP, getMaxSeverity, getSafeSODValue } from '../riskOptUtils';
import { getAllPaths } from '../APImproveModal';
import { correctOccurrence } from './pcOccurrenceMap';
import { recommendOccurrence } from './occurrenceRecommendMap';
import { recommendDetection, D_SCORE_DESCRIPTION } from './detectionRatingMap';
import {
  type ScoredPCIndustry,
  type ScoredDCIndustry,
  findBestPcForSixStep,
  findBestDcForSixStep,
  computeOptimizedOccurrence,
  computeOptimizedDetection,
} from '../../../utils/optimizationOdIndustry';
import { autoFillMissingOccurrence } from '../../../utils/autoFillOccurrence';
import { autoFillMissingDetection } from '../../../utils/autoFillDetection';
import { PLACEHOLDER_NA, PLACEHOLDER_DASH, RECOMMEND_PREFIX } from '../allTabConstants';

interface UseRecommendHandlersParams {
  state: WorksheetState | undefined;
  setState: React.Dispatch<React.SetStateAction<WorksheetState>> | undefined;
  setDirty: React.Dispatch<React.SetStateAction<boolean>> | undefined;
  saveAtomicDB?: (force?: boolean) => void | Promise<void>;
  processedFMGroups: ProcessedFMGroup[];
  globalMaxSeverity: number;
}

/** 모달 상태 */
export interface RecommendModalState {
  isOpen: boolean;
  candidates: RecommendCandidate[];
  cftLeaderName: string;
  diagnostics?: {
    totalFMGroups: number;
    totalRows: number;
    sodMissingCount: number;
    apLCount: number;
    lldMatchedCount?: number;
  };
}

/** 자동생성값 판별 (덮어쓰기 가능): 빈값, "-", "N/A", "[추천]..." */
function isAutoGenerated(val: string): boolean {
  const v = (val || '').trim();
  return !v || v === PLACEHOLDER_DASH || v === PLACEHOLDER_NA || v.startsWith(RECOMMEND_PREFIX);
}

/** Import B5 PC 문자열 → §12 규칙 newO (산업DB 행 매칭 시 industry 우선) */
function newOFromPcText(currentO: number, pcText: string, scored: ScoredPCIndustry[]): number {
  const t = pcText.trim();
  const row = scored.find(
    s => s.method === t || t.includes(s.method) || s.method.includes(t),
  );
  if (row) return computeOptimizedOccurrence(currentO, row.industryO, row.keywordO);
  const co = correctOccurrence(pcText);
  const kwO = co.correctedO ?? recommendOccurrence(pcText);
  return computeOptimizedOccurrence(currentO, null, kwO && kwO > 0 ? kwO : null);
}

/** Import A6 DC 문자열 → §12 규칙 newD */
function newDFromDcText(currentD: number, dcText: string, scored: ScoredDCIndustry[]): number {
  const t = dcText.trim();
  const row = scored.find(
    s => s.method === t || t.includes(s.method) || s.method.includes(t),
  );
  if (row) return computeOptimizedDetection(currentD, row.industryD, row.keywordD);
  const kwD = recommendDetection(dcText);
  return computeOptimizedDetection(currentD, null, kwD > 0 ? kwD : null);
}

export function useRecommendHandlers({
  state, setState, setDirty, saveAtomicDB,
  processedFMGroups, globalMaxSeverity,
}: UseRecommendHandlersParams) {

  // ★ 개선추천 모달 상태
  const [recommendModal, setRecommendModal] = useState<RecommendModalState>({
    isOpen: false, candidates: [], cftLeaderName: '',
  });

  // ★ AP 최단거리 개선 핸들러
  const handleAPImprove = useCallback((targetLevel: 'L' | 'M') => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};

    const uniqueKeys: string[] = [];
    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (row.fcId && fmGroup.fmId) {
          uniqueKeys.push(`${fmGroup.fmId}-${row.fcId}`);
        }
      });
    });

    const { updatedData, stats } = applyAPImprovement(
      riskData, uniqueKeys, globalMaxSeverity, targetLevel,
    );

    if (stats.improved === 0 && stats.unreachable === 0) {
      alert(`개선 대상 없음: 모든 항목이 이미 ${targetLevel === 'L' ? 'L' : 'M 이하'} 등급입니다.`);
      return;
    }

    setState(prev => ({ ...prev, riskData: updatedData as Record<string, string | number> }));
    setDirty?.(true);

    const lines = [
      `[AP 최단거리 개선 완료]`,
      `S(심각도): ${globalMaxSeverity} (고정)`,
      `대상: ${stats.total}건`,
      `개선: ${stats.improved}건`,
    ];
    if (stats.hToL > 0) lines.push(`  H→L: ${stats.hToL}건`);
    if (stats.hToM > 0) lines.push(`  H→M: ${stats.hToM}건`);
    if (stats.mToL > 0) lines.push(`  M→L: ${stats.mToL}건`);
    if (stats.unreachable > 0) lines.push(`개선불가(O=2,D=2에서도 L 미달): ${stats.unreachable}건`);
    lines.push('', '※ O, D 값이 최소 cost로 자동보정되었습니다.');
    lines.push('※ 저장 버튼을 눌러 DB에 반영하세요.');
    alert(lines.join('\n'));
  }, [state, setState, setDirty, processedFMGroups, globalMaxSeverity]);

  // ★ 개선추천 — 모달 열기 (데이터 준비 + 모달 표시)
  const handleRecommendImprovement = useCallback(async () => {
    if (!state || !setState) {
      console.info('[Recommend] state/setState 미준비 — 모달 열기 스킵');
      return;
    }
    if (processedFMGroups.length === 0) {
      alert('고장연결 데이터가 없습니다. 4단계 고장연결을 먼저 완료해주세요.');
      return;
    }

    try {
    const riskData = state.riskData || {};

    // CFT 리더(FMEA 책임자) 이름 가져오기
    let cftLeaderName = '';
    try {
      const fmeaId = state?.fmeaId || new URLSearchParams(window.location.search).get('id') || '';
      if (fmeaId) {
        const infoRes = await fetch(`/api/fmea/info?fmeaId=${encodeURIComponent(fmeaId)}`);
        const infoData = await infoRes.json();
        cftLeaderName = infoData?.fmeaInfo?.responsible || infoData?.fmeaInfo?.fmeaResponsibleName || '';
      }
    } catch (err) { console.error('[Recommend] CFT 리더 조회 실패:', err); }

    // ★ 산업DB + Import B5/A6 병렬 로드
    let scoredPCs: ScoredPCIndustry[] = [];
    let scoredDCs: ScoredDCIndustry[] = [];
    // Import B5(PC)/A6(DC) 직접매칭용 맵
    const fcToPcMap = new Map<string, string[]>();
    const fcToDcMap = new Map<string, string[]>();
    try {
      const fmeaId = state?.fmeaId || new URLSearchParams(window.location.search).get('id') || '';
      const [krPcRes, krDcRes, masterRes] = await Promise.all([
        fetch('/api/kr-industry?type=prevention').then(r => r.json()).catch(() => ({ prevention: [] })),
        fetch('/api/kr-industry?type=detection').then(r => r.json()).catch(() => ({ detection: [] })),
        fmeaId ? fetch(`/api/pfmea/master?fmeaId=${fmeaId}&includeItems=true`, { cache: 'no-store' }).then(r => r.json()).catch(() => null) : Promise.resolve(null),
      ]);
      scoredPCs = ((krPcRes.prevention || []) as { method: string; defaultRating?: number | null }[])
        .filter(e => e.method)
        .map(e => {
          const co = correctOccurrence(e.method);
          const rec = recommendOccurrence(e.method);
          const keywordO =
            co.correctedO != null && co.correctedO > 0
              ? co.correctedO
              : rec != null && rec > 0
                ? rec
                : null;
          const dr = e.defaultRating;
          const industryO =
            dr != null && dr >= 1 && dr <= 10 ? Math.round(dr) : null;
          return { method: e.method, industryO, keywordO };
        });
      scoredDCs = ((krDcRes.detection || []) as {
        method: string;
        methodType?: string;
        defaultRating?: number | null;
      }[])
        .filter(e => e.method)
        .filter(e => {
          const m = (e.methodType || '').trim();
          return !m || m === '자동';
        })
        .map(e => {
          const rd = recommendDetection(e.method);
          const dr = e.defaultRating;
          const industryD =
            dr != null && dr >= 1 && dr <= 10 ? Math.round(dr) : null;
          return {
            method: e.method,
            industryD,
            keywordD: rd > 0 ? rd : null,
          };
        });
      // ★ Import FC↔PC/DC 직접매칭 맵 구축 (B5/A6)
      if (masterRes?.dataset?.failureChains) {
        for (const ch of masterRes.dataset.failureChains as Array<{ processNo?: string; fcValue?: string; pcValue?: string; dcValue?: string }>) {
          const fc = (ch.fcValue || '').trim();
          const pNo = (ch.processNo || '').trim();
          const pc = (ch.pcValue || '').trim().replace(/^P:/, '').trim();
          const dc = (ch.dcValue || '').trim().replace(/^D:/, '').trim();
          if (fc && pc) {
            const key = `${pNo}|${fc}`;
            const list = fcToPcMap.get(key) || [];
            if (!list.includes(pc)) list.push(pc);
            fcToPcMap.set(key, list);
          }
          if (fc && dc) {
            const key = `${pNo}|${fc}`;
            const list = fcToDcMap.get(key) || [];
            if (!list.includes(dc)) list.push(dc);
            fcToDcMap.set(key, list);
          }
        }
      }
    } catch (err) { console.error('[Recommend] 데이터 로드 실패:', err); }

    // ★ SRP: H/M만 대상, L 제외, LLD 매칭 항목 스킵
    const candidates: RecommendCandidate[] = [];
    let totalRows = 0;
    let sodMissingCount = 0;
    let apLCount = 0;
    let lldMatchedCount = 0;

    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (!row.fcId || !fmGroup.fmId) return;
        totalRows++;
        const uk = `${fmGroup.fmId}-${row.fcId}`;
        const s = getSafeSODValue(riskData, `risk-${uk}-S`) || getMaxSeverity(fmGroup.fmId, state);
        const o = getSafeSODValue(riskData, `risk-${uk}-O`);
        const d = getSafeSODValue(riskData, `risk-${uk}-D`);
        const sodComplete = s > 0 && o > 0 && d > 0;
        if (!sodComplete) { sodMissingCount++; return; } // SOD 미입력 → 스킵
        const ap: 'H' | 'M' | 'L' = (calcAP(s, o, d) || 'L');
        if (ap !== 'H' && ap !== 'M') { apLCount++; return; } // ★ L 제외

        // ★ LLD 매칭 항목 스킵 (이미 LLD추천으로 배정된 항목)
        const lessonOpt = ((riskData[`lesson-opt-${uk}`] as string) || '').trim();
        if (lessonOpt && lessonOpt !== '-' && lessonOpt !== 'n/a') {
          lldMatchedCount++;
          return;
        }

        const prevOptKey = `prevention-opt-${uk}`;
        const detOptKey = `detection-opt-${uk}`;
        const curPrevOpt = ((riskData[prevOptKey] as string) || '').trim();
        const curDetOpt = ((riskData[detOptKey] as string) || '').trim();
        const hasPrev = !isAutoGenerated(curPrevOpt);
        const hasDet = !isAutoGenerated(curDetOpt);

        // 5단계 현재 예방관리(PC)/검출관리(DC) 텍스트
        const curPrevText = ((riskData[`prevention-${uk}`] as string) || '').trim();
        const curDetText = ((riskData[`detection-${uk}`] as string) || '').trim();

        // ★ Import 직접매칭 우선 확인 (B5→PC, A6→DC)
        const processNo = (fmGroup.fmProcessNo || '').trim();
        const fcText = (row.fcText || '').trim();
        const directKey = `${processNo}|${fcText}`;
        const directPcList = fcToPcMap.get(directKey);
        const directDcList = fcToDcMap.get(directKey);

        // 추천안 사전 계산 — SOD 있을 때 AP경로, 없어도 Import 직접매칭은 항상 표시
        let prevRecommend = '';
        let detRecommend = '';

        /** 모달 목표 O/D — §12 산출값이 있으면 AP 경로 목표 대신 표시 */
        let suggestedTargetO: number | null = null;
        let suggestedTargetD: number | null = null;

        // ★ SRP: AP경로 기반 최소경로 추천 (SOD 완비 보장 — 위에서 미입력은 return)
        {
          const paths = getAllPaths(s, o, d);
          const effectiveRec = paths.oOnly.feasible ? 'O_ONLY' as const
            : paths.dOnly.feasible ? 'D_ONLY' as const
            : paths.both.feasible ? 'BOTH' as const
            : undefined;
          const needsO = effectiveRec === 'O_ONLY' || effectiveRec === 'BOTH';
          const needsD = effectiveRec === 'D_ONLY' || effectiveRec === 'BOTH';

          if (!hasPrev) {
            if (needsO) {
              // O 개선 필요 → 추천안 산출
              const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly : effectiveRec === 'BOTH' ? paths.both : paths.dOnly;
              if (directPcList && directPcList.length > 0) {
                const neo = newOFromPcText(o, directPcList[0], scoredPCs);
                const showO = Math.min(neo, pathData.targetO);
                suggestedTargetO = showO;
                prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${showO} ${directPcList[0]}`;
              } else {
                const best = findBestPcForSixStep(o, scoredPCs, pathData.targetO);
                if (best) {
                  suggestedTargetO = best.newO;
                  prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${best.newO} ${best.method}`;
                } else {
                  prevRecommend = `${RECOMMEND_PREFIX} 발생도 ${o}→${pathData.targetO} 개선 필요`;
                }
              }
            } else {
              // ★ O 개선 불필요 → N/A
              prevRecommend = PLACEHOLDER_NA;
            }
          }

          if (!hasDet) {
            if (needsD) {
              // D 개선 필요 → 추천안 산출
              const pathData = effectiveRec === 'D_ONLY' ? paths.dOnly : effectiveRec === 'BOTH' ? paths.both : paths.oOnly;
              if (directDcList && directDcList.length > 0) {
                const nd = newDFromDcText(d, directDcList[0], scoredDCs);
                const showD = Math.min(nd, pathData.targetD);
                suggestedTargetD = showD;
                detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${showD} ${directDcList[0]}`;
              } else {
                const best = findBestDcForSixStep(d, scoredDCs, pathData.targetD);
                if (best) {
                  suggestedTargetD = best.newD;
                  detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${best.newD} ${best.method}`;
                } else {
                  detRecommend = `${RECOMMEND_PREFIX} 검출도 ${d}→${pathData.targetD} 개선 필요`;
                }
              }
            } else {
              // ★ D 개선 불필요 → N/A
              detRecommend = PLACEHOLDER_NA;
            }
          }
        }

        // 목표 O'/D' 계산 (AP'=L 달성 기준) + §12 산출 목표 병합
        let targetO = o;
        let targetD = d;
        let targetAP: 'H' | 'M' | 'L' = 'L';
        if (sodComplete) {
          const paths = getAllPaths(s, o, d);
          const pathData = paths.oOnly.feasible ? paths.oOnly
            : paths.dOnly.feasible ? paths.dOnly
            : paths.both.feasible ? paths.both
            : null;
          targetO = pathData ? pathData.targetO : o;
          targetD = pathData ? pathData.targetD : d;
          if (suggestedTargetO !== null) targetO = suggestedTargetO;
          if (suggestedTargetD !== null) targetD = suggestedTargetD;
          targetAP = calcAP(s, targetO, targetD) || 'L';
        }

        candidates.push({
          uniqueKey: uk,
          fmId: fmGroup.fmId,
          fcId: row.fcId,
          processNo: fmGroup.fmProcessNo,
          processName: fmGroup.fmProcessName,
          fmText: fmGroup.fmText,
          fcText: row.fcText,
          s, o, d, ap,
          hasPrev, hasDet,
          prevRecommend, detRecommend,
          curPrevText, curDetText,
          curPrevOpt, curDetOpt,
          targetO, targetD, targetAP,
        });
      });
    });

    // 모달 열기 (진단 정보 포함 — SRP: L 제외, LLD 매칭 제외)
    setRecommendModal({
      isOpen: true, candidates, cftLeaderName,
      diagnostics: {
        totalFMGroups: processedFMGroups.length,
        totalRows,
        sodMissingCount,
        apLCount,
        lldMatchedCount,
      },
    });
    } catch (err) { console.error('[Recommend] 추천 처리 실패:', err); }
  }, [state, setState, processedFMGroups]);

  // ★ 선택적용 핸들러 (모달에서 호출) — checkedKeys로 체크된 행만 적용
  const applyRecommendations = useCallback((options: { prevention: boolean; detection: boolean; checkedKeys?: Set<string> }) => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};
    const { candidates, cftLeaderName } = recommendModal;
    const updates: Record<string, string> = {};
    let count = 0;
    const checkedKeys = options.checkedKeys;

    candidates.forEach(c => {
      const uk = c.uniqueKey;
      // 체크된 행만 적용 (checkedKeys가 없으면 전체 적용 — 호환성)
      if (checkedKeys && !checkedKeys.has(uk)) return;

      const prevKey = `prevention-opt-${uk}`;
      const detKey = `detection-opt-${uk}`;
      const personKey = `person-opt-${uk}`;

      // ★ SRP: 경로 기반 N/A 강제 적용 — needsO=false면 O측=N/A, needsD=false면 D측=N/A
      if (!c.hasPrev) {
        if (c.prevRecommend === PLACEHOLDER_NA) {
          updates[prevKey] = PLACEHOLDER_NA; // O 불필요 → N/A
        } else if (options.prevention && c.prevRecommend) {
          updates[prevKey] = c.prevRecommend;
        }
      }
      if (!c.hasDet) {
        if (c.detRecommend === PLACEHOLDER_NA) {
          updates[detKey] = PLACEHOLDER_NA; // D 불필요 → N/A
        } else if (options.detection && c.detRecommend) {
          updates[detKey] = c.detRecommend;
        }
      }

      // 책임자 자동 배정
      if (cftLeaderName && (updates[prevKey] || updates[detKey])) {
        if (!((riskData[personKey] as string) || '').trim()) {
          updates[personKey] = cftLeaderName;
        }
      }

      if (updates[prevKey] || updates[detKey]) count++;
    });

    if (Object.keys(updates).length === 0) return;

    setState(prev => ({ ...prev, riskData: { ...(prev.riskData || {}), ...updates } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [state, setState, setDirty, saveAtomicDB, recommendModal]);

  // ★ 개별 항목 적용 핸들러 (IndustryImproveModal에서 호출)
  const applySingleRecommendation = useCallback((
    uniqueKey: string, mode: 'prevention' | 'detection', value: string,
  ) => {
    if (!setState) return;
    const key = mode === 'prevention' ? `prevention-opt-${uniqueKey}` : `detection-opt-${uniqueKey}`;
    setState(prev => ({
      ...prev,
      riskData: { ...(prev.riskData || {}), [key]: value },
    }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [setState, setDirty, saveAtomicDB]);

  // ★ 모달 닫기
  const closeRecommendModal = useCallback(() => {
    setRecommendModal(prev => ({ ...prev, isOpen: false }));
  }, []);

  // ★ 발생도(O) 자동재평가 — 1순위: 산업DB, 2순위: 키워드 → 한 번에 합쳐서 setState
  const autoRecommendO = useCallback(async () => {
    if (!state?.riskData || !setState) return;

    const fmeaId = (state as any).fmeaId || new URLSearchParams(typeof window !== 'undefined' ? window.location.search : '').get('id') || '';
    let dbFilled = 0;
    let kwFilled = 0;
    let unmatched = 0;

    // ★ 모든 결과를 하나의 updates에 수집 → 한 번에 setState
    const allUpdates: Record<string, string | number> = {};

    // 1순위: 산업DB 매칭
    const dbMatchedKeys = new Set<string>();
    if (fmeaId) {
      try {
        const res = await fetch('/api/sod/recommend-correction', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ fmeaId, type: 'O' }),
        });
        const json = await res.json();
        if (json.success && json.oRecommendations?.length > 0) {
          for (const rec of json.oRecommendations) {
            if (rec.recommendedValue < 2) continue;
            allUpdates[`risk-${rec.uniqueKey}-O`] = rec.recommendedValue;
            allUpdates[`imported-O-${rec.uniqueKey}`] = 'auto';
            dbMatchedKeys.add(rec.uniqueKey);
            dbFilled++;
          }
        }
        unmatched = json.stats?.o?.unmatched || 0;
      } catch (e) { console.error('[O-Rec] 산업DB API 실패:', e); }
    }

    // 2순위: 키워드 추론 (산업DB에서 이미 매칭된 건은 제외)
    const fls = (state.failureLinks || []).map((fl) => ({
      fmId: String(fl.fmId || ''), fcId: String(fl.fcId || ''),
    }));
    const result = autoFillMissingOccurrence(state.riskData || {}, fls, true);
    for (const detail of result.details) {
      if (detail.oValue < 2) continue;
      if (dbMatchedKeys.has(detail.uniqueKey)) continue; // 산업DB 우선
      allUpdates[`risk-${detail.uniqueKey}-O`] = detail.oValue;
      allUpdates[`imported-O-${detail.uniqueKey}`] = 'auto';
      kwFilled++;
    }

    // ★ 한 번에 setState
    if (Object.keys(allUpdates).length > 0) {
      setState((prev: WorksheetState) => ({
        ...prev,
        riskData: { ...(prev.riskData || {}), ...allUpdates } as Record<string, string | number>,
      }));
    }

    const total = dbFilled + kwFilled;
    const lines = [`[발생도(O) 재평가 완료]`, ``, `산업DB 매칭: ${dbFilled}건`, `키워드 추론: ${kwFilled}건`];
    if (unmatched > 0) lines.push(`DB 미매칭 (누락): ${unmatched}건 — 수동 입력 필요`);
    lines.push(``, `합계: ${total}건 수정`);
    if (total === 0) lines.push(``, `※ 수정 대상이 없습니다.`);
    alert(lines.join('\n'));
    if (total > 0) {
      setDirty?.(true);
      saveAtomicDB?.(true);
    }
  }, [state?.riskData, state?.failureLinks, setState, setDirty, saveAtomicDB, state]);

  // ★ 검출도(D) 자동재평가 — 1순위: 산업DB, 2순위: 키워드 → 한 번에 합쳐서 setState
  const autoRecommendD = useCallback(async () => {
    if (!state?.riskData || !setState) return;

    const fmeaId = (state as any).fmeaId || new URLSearchParams(typeof window !== 'undefined' ? window.location.search : '').get('id') || '';
    let dbFilled = 0;
    let kwFilled = 0;
    let unmatched = 0;

    const allUpdates: Record<string, string | number> = {};
    const dbMatchedKeys = new Set<string>();

    // 1순위: 산업DB 매칭
    if (fmeaId) {
      try {
        const res = await fetch('/api/sod/recommend-correction', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ fmeaId, type: 'D' }),
        });
        const json = await res.json();
        if (json.success && json.dRecommendations?.length > 0) {
          for (const rec of json.dRecommendations) {
            if (rec.recommendedValue < 2) continue;
            allUpdates[`risk-${rec.uniqueKey}-D`] = rec.recommendedValue;
            allUpdates[`imported-D-${rec.uniqueKey}`] = 'auto';
            dbMatchedKeys.add(rec.uniqueKey);
            dbFilled++;
          }
        }
        unmatched = json.stats?.d?.unmatched || 0;
      } catch (e) { console.error('[D-Rec] 산업DB API 실패:', e); }
    }

    // 2순위: 키워드 추론 (산업DB 매칭 건 제외)
    const fls = (state.failureLinks || []).map((fl) => ({
      fmId: String(fl.fmId || ''), fcId: String(fl.fcId || ''),
    }));
    const result = autoFillMissingDetection(state.riskData || {}, fls, true);
    for (const detail of result.details) {
      if (detail.dValue < 2) continue;
      if (dbMatchedKeys.has(detail.uniqueKey)) continue;
      allUpdates[`risk-${detail.uniqueKey}-D`] = detail.dValue;
      allUpdates[`imported-D-${detail.uniqueKey}`] = 'auto';
      kwFilled++;
    }

    // ★ 한 번에 setState
    if (Object.keys(allUpdates).length > 0) {
      setState((prev: WorksheetState) => ({
        ...prev,
        riskData: { ...(prev.riskData || {}), ...allUpdates } as Record<string, string | number>,
      }));
    }

    const total = dbFilled + kwFilled;
    const lines = [`[검출도(D) 재평가 완료]`, ``, `산업DB 매칭: ${dbFilled}건`, `키워드 추론: ${kwFilled}건`];
    if (unmatched > 0) lines.push(`DB 미매칭 (누락): ${unmatched}건 — 수동 입력 필요`);
    lines.push(``, `합계: ${total}건 수정`);
    if (total === 0) lines.push(``, `※ 수정 대상이 없습니다.`);
    alert(lines.join('\n'));
    if (total > 0) {
      setDirty?.(true);
      saveAtomicDB?.(true);
    }
  }, [state?.riskData, state?.failureLinks, setState, setDirty, saveAtomicDB, state]);

  return {
    handleAPImprove,
    handleRecommendImprovement,
    autoRecommendO,
    autoRecommendD,
    // ★ 모달 관련
    recommendModal,
    closeRecommendModal,
    applyRecommendations,
    applySingleRecommendation,
  };
}
