/**
 * @file mock-data.ts
 * @description PFMEA 워크시트 샘플 데이터
 * @version 1.0.0
 * @created 2025-12-26
 */

import { createEmptyRow, type PFMEAWorksheetRow, type PFMEAHeader } from './types';

/** 샘플 헤더 정보 */
export const SAMPLE_HEADER: PFMEAHeader = {
  company: '타이어 주식회사',
  customer: 'OEM 고객사',
  plant: '본사 공장',
  productProgram: 'PCR 225/45R17',
  fmeaId: 'PFMEA-2025-0001',
  startDate: '2025-01-01',
  revisionNo: 1,
  responsibility: '품질보증팀장',
  securityLevel: 'Confidential',
  approvalList: ['품질담당', '생산담당', '기술담당'],
};

/** 샘플 워크시트 데이터 */
export const SAMPLE_DATA: PFMEAWorksheetRow[] = [
  {
    ...createEmptyRow(),
    id: 'row_1',
    revisionNo: '1.0',
    changeHistory: '최초 작성',
    productName: 'PCR 225/45R17',
    processName: '10. 정련',
    workElement: '밴버리 믹서',
    category4M: 'MC',
    workElementDetail: '1차 정련기',
    productRequirement: '균일한 고무 배합',
    requirement: '배합 레시피 준수',
    processFunction: '원료 혼합 및 가소화',
    productChar: '고무 경도',
    workElementFunc: '원료 투입 및 혼합',
    workElementFunc2: '',
    processChar: '믹싱 온도',
    processChar2: '믹싱 시간',
    processChar3: '',
    failureNaming: 'FM-001',
    failureEffect: '제품 경도 불균일로 인한 성능 저하',
    severity: 7,
    failureMode: '배합 불균일',
    workElementFC: '밴버리 믹서',
    failureCause: '원료 계량 오차',
    failureCause2: '',
    preventionControl: '원료 자동계량 시스템',
    occurrence: 4,
    detectionControl: 'MSS 검사',
    detection: 5,
    ap: 'M',
    specialChar: 'SC',
    remarks: '',
    improvementPlan: '',
    preventionAction: '',
    detectionAction: '',
    responsiblePerson: '',
    targetDate: '',
    status: '',
    actionTaken: '',
    completionDate: '',
    severityAfter: null,
    occurrenceAfter: null,
    detectionAfter: null,
    specialCharAfter: '',
    apAfter: '',
    remarksAfter: '',
  },
  {
    ...createEmptyRow(),
    id: 'row_2',
    revisionNo: '1.0',
    changeHistory: '',
    productName: 'PCR 225/45R17',
    processName: '20. 압출',
    workElement: '압출기',
    category4M: 'MC',
    workElementDetail: 'T/W 압출기',
    productRequirement: '정확한 단면 형상',
    requirement: '규격 치수 준수',
    processFunction: '트레드 압출 성형',
    productChar: '트레드 치수',
    workElementFunc: '고무 압출 및 성형',
    workElementFunc2: '',
    processChar: '압출 온도',
    processChar2: '압출 속도',
    processChar3: 'Die 압력',
    failureNaming: 'FM-002',
    failureEffect: '트레드 치수 불량으로 인한 성형 불가',
    severity: 8,
    failureMode: '치수 과다/과소',
    workElementFC: '압출기 Die',
    failureCause: 'Die 마모',
    failureCause2: '온도 편차',
    preventionControl: 'Die 주기 교체',
    occurrence: 3,
    detectionControl: '인라인 치수 측정',
    detection: 3,
    ap: 'M',
    specialChar: 'CC',
    remarks: '',
    improvementPlan: '',
    preventionAction: '',
    detectionAction: '',
    responsiblePerson: '',
    targetDate: '',
    status: '',
    actionTaken: '',
    completionDate: '',
    severityAfter: null,
    occurrenceAfter: null,
    detectionAfter: null,
    specialCharAfter: '',
    apAfter: '',
    remarksAfter: '',
  },
  {
    ...createEmptyRow(),
    id: 'row_3',
    revisionNo: '1.0',
    changeHistory: '',
    productName: 'PCR 225/45R17',
    processName: '30. 압연',
    workElement: '압연기',
    category4M: 'MC',
    workElementDetail: '캘린더',
    productRequirement: '균일한 시트 두께',
    requirement: '두께 공차 ±0.1mm',
    processFunction: '고무 시트 성형',
    productChar: '시트 두께',
    workElementFunc: '롤 간격 조절 및 압연',
    workElementFunc2: '',
    processChar: '롤 온도',
    processChar2: '롤 간격',
    processChar3: '라인 속도',
    failureNaming: 'FM-003',
    failureEffect: '시트 두께 불균일로 인한 중량 편차',
    severity: 6,
    failureMode: '두께 편차',
    workElementFC: '캘린더 롤',
    failureCause: '롤 온도 불균일',
    failureCause2: '',
    preventionControl: '롤 온도 자동제어',
    occurrence: 4,
    detectionControl: '두께 게이지 측정',
    detection: 4,
    ap: 'M',
    specialChar: 'SC',
    remarks: '',
    improvementPlan: '',
    preventionAction: '',
    detectionAction: '',
    responsiblePerson: '',
    targetDate: '',
    status: '',
    actionTaken: '',
    completionDate: '',
    severityAfter: null,
    occurrenceAfter: null,
    detectionAfter: null,
    specialCharAfter: '',
    apAfter: '',
    remarksAfter: '',
  },
  {
    ...createEmptyRow(),
    id: 'row_4',
    revisionNo: '1.0',
    changeHistory: '',
    productName: 'PCR 225/45R17',
    processName: '40. 성형',
    workElement: '성형기',
    category4M: 'MC',
    workElementDetail: '1차 성형기',
    productRequirement: '정확한 G/T 조립',
    requirement: '조립 위치 정도',
    processFunction: '그린타이어 조립',
    productChar: 'G/T 형상',
    workElementFunc: '부재료 부착 및 성형',
    workElementFunc2: '드럼 회전 제어',
    processChar: '드럼 폭',
    processChar2: '텐션',
    processChar3: '회전 속도',
    failureNaming: 'FM-004',
    failureEffect: '조인트 불량으로 인한 분리',
    severity: 9,
    failureMode: '조인트 불량',
    workElementFC: '성형 드럼',
    failureCause: '조인트 길이 부족',
    failureCause2: '작업자 숙련도',
    preventionControl: '조인트 길이 검증',
    occurrence: 5,
    detectionControl: '조인트 검사',
    detection: 4,
    ap: 'H',
    specialChar: 'CC',
    remarks: '안전 관련 항목',
    improvementPlan: '자동 조인트 검증 시스템 도입',
    preventionAction: '센서 기반 조인트 검증',
    detectionAction: '비전 검사 도입',
    responsiblePerson: '생산기술팀',
    targetDate: '2025-03-31',
    status: 'In Progress',
    actionTaken: '',
    completionDate: '',
    severityAfter: null,
    occurrenceAfter: null,
    detectionAfter: null,
    specialCharAfter: '',
    apAfter: '',
    remarksAfter: '',
  },
  {
    ...createEmptyRow(),
    id: 'row_5',
    revisionNo: '1.0',
    changeHistory: '',
    productName: 'PCR 225/45R17',
    processName: '50. 가류',
    workElement: '가류기',
    category4M: 'MC',
    workElementDetail: 'Segmented Mold',
    productRequirement: '균일한 가류도',
    requirement: '가류 조건 준수',
    processFunction: '타이어 가류 성형',
    productChar: '가류도',
    workElementFunc: '열/압력 인가',
    workElementFunc2: '금형 개폐',
    processChar: '가류 온도',
    processChar2: '가류 시간',
    processChar3: '가류 압력',
    failureNaming: 'FM-005',
    failureEffect: '미가류로 인한 내구성 저하',
    severity: 8,
    failureMode: '미가류/과가류',
    workElementFC: '가류기 히터',
    failureCause: '온도 센서 오작동',
    failureCause2: '',
    preventionControl: '센서 정기 교정',
    occurrence: 2,
    detectionControl: '경도 검사',
    detection: 3,
    ap: 'M',
    specialChar: 'CC',
    remarks: '',
    improvementPlan: '',
    preventionAction: '',
    detectionAction: '',
    responsiblePerson: '',
    targetDate: '',
    status: '',
    actionTaken: '',
    completionDate: '',
    severityAfter: null,
    occurrenceAfter: null,
    detectionAfter: null,
    specialCharAfter: '',
    apAfter: '',
    remarksAfter: '',
  },
];

/** 10개 빈 행 생성 */
export function createEmptyRows(count: number = 10): PFMEAWorksheetRow[] {
  return Array.from({ length: count }, (_, i) => ({
    ...createEmptyRow(),
    id: `empty_${i}`,
  }));
}

/** 초기 데이터 (샘플 + 빈 행) */
export function getInitialData(): PFMEAWorksheetRow[] {
  return [...SAMPLE_DATA, ...createEmptyRows(5)];
}













