/**
 * @file auto-generated-cleanup.spec.ts
 * @description "(자동생성)" 데이터가 DB에서 제거되고 워크시트에 표시되지 않는지 검증
 */

import { test, expect } from '@playwright/test';

const BASE_URL = 'http://localhost:3000';
const TEST_FMEA_ID = 'PFM26-M001'; // 대문자 유지 (API에서 소문자로 변환됨)

test.describe('자동생성 데이터 정리 테스트', () => {
  
  test('API 로드 시 "(자동생성)" 데이터가 필터링되어야 함', async ({ request }) => {
    // 1. FMEA 데이터 로드
    const response = await request.get(`${BASE_URL}/api/fmea?fmeaId=${TEST_FMEA_ID}`);
    expect(response.ok()).toBeTruthy();
    
    const data = await response.json();
    console.log('=== API 응답 데이터 검사 ===');
    
    // 2. l2 배열 내 l3.functions 검사
    let autoGeneratedCount = 0;
    
    if (data.l2 && Array.isArray(data.l2)) {
      data.l2.forEach((proc: any, procIdx: number) => {
        // l3 (작업요소) 내 functions 검사
        if (proc.l3 && Array.isArray(proc.l3)) {
          proc.l3.forEach((we: any, weIdx: number) => {
            if (we.functions && Array.isArray(we.functions)) {
              we.functions.forEach((f: any, fIdx: number) => {
                if (f.name && f.name.includes('자동생성')) {
                  console.log(`❌ 발견: l2[${procIdx}].l3[${weIdx}].functions[${fIdx}].name = "${f.name}"`);
                  autoGeneratedCount++;
                }
              });
            }
          });
        }
        
        // functions (메인공정기능) 검사
        if (proc.functions && Array.isArray(proc.functions)) {
          proc.functions.forEach((f: any, fIdx: number) => {
            if (f.name && f.name.includes('자동생성')) {
              console.log(`❌ 발견: l2[${procIdx}].functions[${fIdx}].name = "${f.name}"`);
              autoGeneratedCount++;
            }
          });
        }
      });
    }
    
    // 3. l1.types 내 functions 검사
    if (data.l1 && data.l1.types && Array.isArray(data.l1.types)) {
      data.l1.types.forEach((type: any, typeIdx: number) => {
        if (type.functions && Array.isArray(type.functions)) {
          type.functions.forEach((f: any, fIdx: number) => {
            if (f.name && f.name.includes('자동생성')) {
              console.log(`❌ 발견: l1.types[${typeIdx}].functions[${fIdx}].name = "${f.name}"`);
              autoGeneratedCount++;
            }
          });
        }
      });
    }
    
    console.log(`\n=== 결과: "(자동생성)" 데이터 ${autoGeneratedCount}건 발견 ===`);
    
    // 4. 검증: "(자동생성)" 데이터가 0건이어야 함
    expect(autoGeneratedCount).toBe(0);
  });

  test('워크시트 UI에서 "(자동생성)" 텍스트가 보이지 않아야 함', async ({ page }) => {
    // 1. 워크시트 페이지 이동
    await page.goto(`${BASE_URL}/pfmea/worksheet?fmeaId=${TEST_FMEA_ID}&tab=function-l3`);
    
    // 2. 페이지 로드 대기
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);
    
    // 3. "(자동생성)" 텍스트 검색
    const autoGeneratedElements = await page.locator('text=자동생성').all();
    
    console.log(`\n=== UI 검사: "(자동생성)" 텍스트 ${autoGeneratedElements.length}개 발견 ===`);
    
    for (const el of autoGeneratedElements) {
      const text = await el.textContent();
      console.log(`❌ UI에서 발견: "${text}"`);
    }
    
    // 4. 검증: "(자동생성)" 텍스트가 없어야 함
    expect(autoGeneratedElements.length).toBe(0);
  });

  test('저장 후 "(자동생성)" 데이터가 DB에서 제거되어야 함', async ({ request }) => {
    // 1. 현재 데이터 로드
    const loadResponse = await request.get(`${BASE_URL}/api/fmea?fmeaId=${TEST_FMEA_ID}`);
    const currentData = await loadResponse.json();
    
    // 2. 테스트용 "(자동생성)" 데이터 추가
    const testData = JSON.parse(JSON.stringify(currentData));
    if (testData.l2 && testData.l2[0] && testData.l2[0].l3 && testData.l2[0].l3[0]) {
      if (!testData.l2[0].l3[0].functions) {
        testData.l2[0].l3[0].functions = [];
      }
      testData.l2[0].l3[0].functions.push({
        id: 'test-auto-gen-' + Date.now(),
        name: '(자동생성)',
        processChars: []
      });
    }
    
    // 3. 저장 요청
    const saveResponse = await request.post(`${BASE_URL}/api/fmea`, {
      data: {
        fmeaId: TEST_FMEA_ID,
        legacyData: testData
      }
    });
    expect(saveResponse.ok()).toBeTruthy();
    
    // 4. 다시 로드
    const reloadResponse = await request.get(`${BASE_URL}/api/fmea?fmeaId=${TEST_FMEA_ID}`);
    const reloadedData = await reloadResponse.json();
    
    // 5. "(자동생성)" 데이터가 제거되었는지 확인
    let foundAutoGenerated = false;
    if (reloadedData.l2) {
      reloadedData.l2.forEach((proc: any) => {
        if (proc.l3) {
          proc.l3.forEach((we: any) => {
            if (we.functions) {
              we.functions.forEach((f: any) => {
                if (f.name && f.name.includes('자동생성')) {
                  foundAutoGenerated = true;
                  console.log(`❌ 저장 후에도 남아있음: "${f.name}"`);
                }
              });
            }
          });
        }
      });
    }
    
    expect(foundAutoGenerated).toBe(false);
  });
});
