/**
 * @file types.ts
 * @description 연동 컴포넌트 타입 정의
 * @version 1.0.0
 * @created 2026-01-27
 */

// 연동 모듈 타입
export type LinkageModuleType = 'APQP' | 'FMEA' | 'PFDL' | 'CP';

// 연동 색상 설정
export const LINKAGE_COLORS: Record<LinkageModuleType, { bg: string; bgHover: string; text: string; border: string }> = {
    APQP: { bg: 'bg-green-500', bgHover: 'hover:bg-green-600', text: 'text-green-700', border: 'border-green-300' },
    FMEA: { bg: 'bg-yellow-500', bgHover: 'hover:bg-yellow-600', text: 'text-yellow-700', border: 'border-yellow-300' },
    PFDL: { bg: 'bg-violet-500', bgHover: 'hover:bg-violet-600', text: 'text-violet-700', border: 'border-violet-300' },
    CP: { bg: 'bg-teal-500', bgHover: 'hover:bg-teal-600', text: 'text-teal-700', border: 'border-teal-300' },
};

// 연동 URL 설정
export const LINKAGE_URLS: Record<LinkageModuleType, string> = {
    APQP: '/apqp/register',
    FMEA: '/pfmea/register',
    PFDL: '/pfd/register',
    CP: '/control-plan/register',
};

// LinkageTag Props
export interface LinkageTagProps {
    type: LinkageModuleType;
    id: string;
    locked?: boolean;
    onRemove?: () => void;
    onNavigate?: () => void;
    showRemoveButton?: boolean;
}

// LinkageSection Props
export interface LinkageSectionProps {
    // 현재 모듈 정보
    currentModule: 'APQP' | 'PFMEA' | 'PFD' | 'CP';
    currentId: string;

    // 연동 정보
    apqpNo?: string | null;
    pfmeaId?: string | null;
    pfdNo?: string | null;
    cpNos?: string[];  // 1:N 지원

    // 변경 핸들러
    onApqpChange?: (id: string | null) => void;
    onFmeaChange?: (id: string | null) => void;
    onPfdChange?: (id: string | null) => void;
    onCpAdd?: (id: string) => void;
    onCpRemove?: (id: string) => void;

    // 선택 모달 열기
    onOpenApqpModal?: () => void;
    onOpenFmeaModal?: () => void;
    onOpenPfdModal?: () => void;
    onOpenCpModal?: () => void;

    // 잠금 상태
    locked?: {
        apqp?: boolean;
        fmea?: boolean;
        pfd?: boolean;
        cp?: boolean;
    };

    // 표시 설정 (현재 모듈에 따라 자동 설정)
    show?: {
        apqp?: boolean;
        fmea?: boolean;
        pfd?: boolean;
        cp?: boolean;
    };
}

// =====================================================
// LinkageModal 표준 타입 (v2.0)
// =====================================================

export type SourceModule = 'apqp' | 'pfm' | 'dfm' | 'pfd' | 'cp';
export type TargetModule = 'pfm' | 'pfd' | 'cp';
export type DocType = 'M' | 'F' | 'P' | 'D' | 'T' | 'L' | 'S';  // D: DFMEA, P: PFD, T: Trial, L: Launch, S: Service

/**
 * 연동 문서 아이템
 */
export interface LinkedDocItem {
    id: string;             // 예: pfd26-m001-L01
    module: TargetModule;   // pfd, cp
    docType: DocType;       // M, F, P (또는 CP: T, L, P, S)
    subject?: string;       // 제목 (동기화 시 자동)
    linkGroupNo: number;    // 0=Solo, 1~99=Linked
    isAutoGenerated: boolean; // 자동생성 여부 (L01)
    status: 'linked' | 'solo' | 'pending';
}

/**
 * 소스 문서 정보 (등록정보 공유용)
 */
export interface SourceDocInfo {
    id: string;
    module: SourceModule;
    subject: string;
    customerName?: string;
    modelYear?: string;
    companyName?: string;
    docType: DocType;
}

/**
 * LinkageModal Props
 */
export interface LinkageModalProps {
    isOpen: boolean;
    onClose: () => void;

    // 소스 문서 정보
    sourceInfo: SourceDocInfo;

    // 연동 리스트
    linkedPfdList: LinkedDocItem[];
    linkedCpList: LinkedDocItem[];
    linkedPfmeaList?: LinkedDocItem[];  // ★ DFMEA → PFMEA 연동

    // 이벤트 핸들러 (v2.0: 자동 생성 ID 지원)
    onAddLinkedDoc: (targetModule: TargetModule, generatedId?: string) => void;
    onRemoveLinkedDoc: (docId: string, targetModule: TargetModule) => void;
    onToggleLinkage: (docId: string, isLinked: boolean, targetModule: TargetModule) => void;

    // 연동 대상 설정 (모듈별로 다름)
    showPfdSection?: boolean;
    showCpSection?: boolean;
    showPfmeaSection?: boolean;  // ★ DFMEA에서 PFMEA 연동 섹션 표시
}

// =====================================================
// 유틸리티 함수
// =====================================================

/**
 * 연동 그룹 번호 추출
 */
export function extractLinkGroupNo(docId: string): number {
    const match = docId.match(/-L(\d{2})$/i);
    return match ? parseInt(match[1]) : 0;
}

/**
 * 연동 상태 확인
 */
export function isLinked(docId: string): boolean {
    return /-L\d{2}$/i.test(docId);
}

/**
 * ID를 연동 상태로 변환
 */
export function setLinkedId(docId: string, linkGroupNo: number = 1): string {
    const base = docId.replace(/-(L\d{2}|S)$/i, '');
    return `${base}-L${String(linkGroupNo).padStart(2, '0')}`;
}

/**
 * ID를 단독 상태로 변환
 */
export function setSoloId(docId: string): string {
    const base = docId.replace(/-(L\d{2}|S)$/i, '');
    return `${base}-S`;
}

/**
 * 다음 연동 그룹 번호 계산
 */
export function getNextLinkGroupNo(docs: LinkedDocItem[]): number {
    const linkedDocs = docs.filter(d => d.linkGroupNo > 0);
    if (linkedDocs.length === 0) return 1;
    const maxNo = Math.max(...linkedDocs.map(d => d.linkGroupNo));
    return maxNo + 1;
}
