/**
 * @file types.ts
 * @description STEP B 전처리 파서 타입 정의
 * @created 2026-03-05
 */

// ── 경고 시스템 ──

export type WarningLevel = 'INFO' | 'WARN' | 'ERROR';

export interface StepBWarning {
  level: WarningLevel;
  code: string;
  message: string;
  row?: number;
  value?: string;
}

// ── 컬럼 감지 ──

export interface StepBColumnSpec {
  /** 필드명 (예: 'l1_name', 'proc_name', 'fe', 'fm', 'fc') */
  field: string;
  /** 감지 키워드 목록 (OR 조건) */
  keywords: string[];
  /** N번째 출현 (중복 헤더 구분: 4M, 작업요소, 구분) */
  occurrence: number;
}

export interface StepBColumnMap {
  [field: string]: number | undefined;
}

// ── 파싱된 행 ──

export interface StepBRawRow {
  /** 엑셀 원본 행 번호 (1-based) */
  excelRow: number;
  /** 공정번호 (추출됨) */
  procNo: string;
  /** 원본 필드값 */
  l1Name: string;
  procName: string;
  l1_4m: string;
  l1We: string;
  l1Scope: string;
  l1Func: string;
  l2Func: string;
  l2_4m: string;
  l2We: string;
  l2ElemFunc: string;
  feScope: string;
  fe: string;
  s: string;
  fm: string;
  fc4m: string;
  fcWe: string;
  fc: string;
  pc: string;
  o: string;
  dc: string;
  d: string;
  ap: string;
  sc: string;
  /** 정규화된 값 */
  feNorm: string;
  feScopeNorm: string;
  fmNorm: string;
  fcNorm: string;
  weNorm: string;
  sInt: number | null;
  oInt: number | null;
  dInt: number | null;
  scNorm: string;
}

// ── 빌드 결과 ──

export interface StepBBuildData {
  procMaster: Map<string, string>;  // procNo → processName
  c1: string[];                      // scope 목록 (YP, SP, USER)
  c2: Map<string, string[]>;         // scope → 제품기능[] (l1Func)
  c3: Map<string, string[]>;         // scope → 요구사항[] (l1Func 기반 자동생성)
  c4: StepBC4Item[];                 // 고장영향 (scope + fe + maxS)
  a3: Map<string, { func: string; auto: boolean }>;
  a4: Map<string, StepBA4Item[]>;
  a5: Map<string, string[]>;         // procNo → FM[]
  a5ParentA4?: Map<string, string>;   // `pno|fm` → a4Char (A5→A4 부모 매핑)
  a6: Map<string, string[]>;         // procNo → DC[] (검출관리)
  b1: Map<string, StepBB1Item[]>;
  b2: Map<string, StepBB2Item[]>;
  b3: Map<string, StepBB3Item[]>;
  b4: Map<string, StepBB4Item[]>;
  b5: Map<string, StepBB5Item[]>;    // procNo → PC[] (예방관리)
  fcChains: StepBFCChain[];
}

export interface StepBC4Item {
  procNo: string;
  scope: string;
  fe: string;
  s: number | null;
}

export interface StepBA4Item {
  char: string;
  sc: string;
}

export interface StepBB1Item {
  m4: string;
  we: string;
}

export interface StepBB2Item {
  m4: string;
  we: string;
  func: string;
}

export interface StepBB3Item {
  m4: string;
  we: string;
  char: string;
  sc: string;
}

export interface StepBB4Item {
  m4: string;
  we: string;
  fc: string;
  /** 연결된 FM 텍스트 (1 FC → N FM 패턴 지원: 동일 FC가 여러 FM에 연결될 때 구분) */
  fm: string;
}

export interface StepBB5Item {
  m4: string;
  pc: string;
}

export interface StepBFCChain {
  procNo: string;
  m4: string;
  we: string;
  fe: string;
  fm: string;
  fc: string;
  pc: string;
  dc: string;
  s: number | null;
  o: number | null;
  d: number | null;
  ap: string;
  // UUID 연동 필드 (H-3)
  id?: string;
  fmId?: string;
  feId?: string;
  fcId?: string;
  parentId?: string;
  mergeGroupId?: string;
  // ★★★ 2026-03-17: flatData ID 직접 참조 (결정론적 매핑) ★★★
  fmFlatId?: string;
  fcFlatId?: string;
  feFlatId?: string;
  // ★★★ 2026-03-17: MAIN시트 텍스트 사전 매칭 결과 (buildImportData에서 설정) ★★★
  matchedFmText?: string;   // a5Map에서 매칭된 MAIN시트 FM 텍스트
  matchedFcText?: string;   // b4Map에서 매칭된 MAIN시트 FC 텍스트
}

// ── 최종 결과 ──

export interface StepBConvertResult {
  /** ImportedFlatData[] 호환 데이터 */
  flatData: import('../types').ImportedFlatData[];
  /** MasterFailureChain[] 호환 데이터 */
  failureChains: StepBMasterChain[];
  /** 경고 목록 */
  warnings: StepBWarning[];
  /** 통계 */
  statistics: StepBStatistics;
}

export interface StepBMasterChain {
  processNo: string;
  m4: string;
  fcValue: string;
  fmValue: string;
  feValue: string;
  pcValue: string;
  dcValue: string;
  feScope: string;
  s: number | null;
  o: number | null;
  d: number | null;
  ap: string;
  /** B1 작업요소명 (ParseStatisticsPanel B2 카운트용) */
  workElement?: string;
  /** B2 요소기능 (ParseStatisticsPanel B2 카운트용) */
  l3Function?: string;
  /** B3 공정특성 (ParseStatisticsPanel B3 카운트용) */
  processChar?: string;
  // UUID 연동 필드 (H-3)
  id?: string;
  fmId?: string;
  feId?: string;
  fcId?: string;
  // ★★★ 2026-03-17: flatData ID 직접 참조 (결정론적 매핑) ★★★
  fmFlatId?: string;
  fcFlatId?: string;
  feFlatId?: string;
}

export interface StepBStatistics {
  totalRows: number;
  processCount: number;
  fmCount: number;
  fcCount: number;
  feCount: number;
  dcCount: number;
  pcCount: number;
  chainCount: number;
  autoGeneratedCount: number;
}

// ── 경고 수집기 ──

export class WarningCollector {
  private items: StepBWarning[] = [];

  add(level: WarningLevel, code: string, message: string, row?: number, value?: string): void {
    this.items.push({ level, code, message, row, value });
  }

  info(code: string, message: string, row?: number, value?: string): void {
    this.add('INFO', code, message, row, value);
  }

  warn(code: string, message: string, row?: number, value?: string): void {
    this.add('WARN', code, message, row, value);
  }

  error(code: string, message: string, row?: number, value?: string): void {
    this.add('ERROR', code, message, row, value);
  }

  getAll(): StepBWarning[] {
    return [...this.items];
  }

  summary(): Record<WarningLevel, number> {
    const counts: Record<WarningLevel, number> = { INFO: 0, WARN: 0, ERROR: 0 };
    for (const item of this.items) {
      counts[item.level]++;
    }
    return counts;
  }
}
