/**
 * @file hooks/useRegisterPageHandlers.ts
 * @description DFMEA 등록 페이지 - 모든 핸들러 함수 (저장, 연동, 선택, 검증)
 * @module pfmea/register
 * @created 2026-02-10 page.tsx 분리 리팩토링
 */

'use client';

import { useCallback, useState } from 'react';
import { UserInfo } from '@/types/user';
import { TargetModule } from '@/components/linkage/types';
import { FMEAInfo, FMEAType, FMEASelectType } from '../types';
import { generateFMEAIdFromDB, syncToLocalStorage } from '../utils';
import { useRegisterPageCore } from './useRegisterPageCore';
import { REQUIRED_ROLES } from '@/components/tables/CFTRegistrationTable';
import { toast } from '@/hooks/useToast';

type CoreReturn = ReturnType<typeof useRegisterPageCore>;

export function useRegisterPageHandlers(core: CoreReturn) {
  const {
    user, router, editId, revParam, isEditMode, isRevisionMode,
    fmeaId, setFmeaId, fmeaInfo, setFmeaInfo,
    cftMembers, setCftMembers, saveStatus, setSaveStatus,
    setShowMasterReview,
    fmeaSelectType, setFmeaSelectType,
    availableFmeas, setAvailableFmeas,
    selectedBaseFmea, setSelectedBaseFmea,
    selectedParentApqp, setSelectedParentApqp,
    apqpList, setApqpList, setApqpModalOpen,
    linkedPfdList, setLinkedPfdList,
    linkedCpList, setLinkedCpList,
    fmeaNameList, setFmeaNameList,
    fmeaNameSearch, setFmeaNameSearch,
    duplicateWarning, setDuplicateWarning,
    originalData, setOriginalData,
    setFmeaSelectModalOpen, setFmeaNameModalOpen,
    setIsCreateModalOpen, setLinkageModalOpen,
    setUserModalOpen, setSelectedMemberIndex,
    userModalTarget, setUserModalTarget,
    recordAccessLog, loadAccessLogs,
  } = core;

  // CFT 미입력 경고 모달 상태
  const [cftAlertRoles, setCftAlertRoles] = useState<string[]>([]);

  // =====================================================
  // 필드 업데이트
  // =====================================================
  const updateField = useCallback((field: keyof FMEAInfo, value: string) => {
    setFmeaInfo(prev => ({ ...prev, [field]: value }));
  }, [setFmeaInfo]);

  const handlePartNameChange = useCallback((value: string) => {
    setFmeaInfo(prev => ({
      ...prev,
      partName: value,
    }));
  }, [setFmeaInfo]);

  // =====================================================
  // 연동 문서 핸들러
  // =====================================================
  const handleAddLinkedDoc = useCallback((targetModule: TargetModule, generatedId?: string) => {
    if (targetModule === 'pfd') {
      const newId = generatedId || fmeaId.replace(/^pfm/i, 'pfd');
      const groupNo = linkedPfdList.length + 1;
      setLinkedPfdList(prev => [...prev, {
        id: newId, module: 'pfd', docType: fmeaInfo.fmeaType,
        subject: fmeaInfo.subject, linkGroupNo: groupNo, isAutoGenerated: false, status: 'linked'
      }]);
    } else if (targetModule === 'cp') {
      const newId = generatedId || fmeaId.replace(/^pfm/i, 'cp');
      const groupNo = linkedCpList.length + 1;
      setLinkedCpList(prev => [...prev, {
        id: newId, module: 'cp', docType: 'P',
        subject: fmeaInfo.subject, linkGroupNo: groupNo, isAutoGenerated: false, status: 'linked'
      }]);
    }
  }, [fmeaId, linkedPfdList.length, linkedCpList.length, fmeaInfo.fmeaType, fmeaInfo.subject, setLinkedPfdList, setLinkedCpList]);

  const handleRemoveLinkedDoc = useCallback((docId: string, targetModule: TargetModule) => {
    if (targetModule === 'pfd') setLinkedPfdList(prev => prev.filter(d => d.id !== docId));
    else if (targetModule === 'cp') setLinkedCpList(prev => prev.filter(d => d.id !== docId));
  }, [setLinkedPfdList, setLinkedCpList]);

  const handleToggleLinkage = useCallback((docId: string, isLinked: boolean, targetModule: TargetModule) => {
    const setter = targetModule === 'pfd' ? setLinkedPfdList : setLinkedCpList;
    setter(prev => prev.map(d => d.id === docId ? { ...d, status: isLinked ? 'linked' : 'solo' } : d));
  }, [setLinkedPfdList, setLinkedCpList]);

  // =====================================================
  // FMEA 선택 모달
  // =====================================================
  const openFmeaSelectModal = useCallback(async (type: FMEASelectType) => {
    let projects: any[] = [];
    try {
      const res = await fetch('/api/fmea/projects?type=D');
      const data = await res.json();
      if (data.success && data.projects?.length > 0) projects = data.projects;
    } catch (e) { console.error('[FMEA 프로젝트 조회] 오류:', e); toast.error('FMEA 프로젝트 목록을 불러오는데 실패했습니다.'); }

    if (type === 'MF') {
      const year = new Date().getFullYear().toString().slice(-2);
      const prefix = fmeaId?.startsWith('dfm') ? 'dfm' : 'pfm';
      const defaultMasterId = `${prefix}${year}-m001`;
      const defaultFamilyId = `${prefix}${year}-f001`;
      if (!projects.some((p: any) => p.id?.toLowerCase() === defaultMasterId))
        projects.push({ id: defaultMasterId, fmeaType: 'M', fmeaInfo: { subject: 'Master FMEA (기본)' } });
      if (!projects.some((p: any) => p.id?.toLowerCase() === defaultFamilyId))
        projects.push({ id: defaultFamilyId, fmeaType: 'F', fmeaInfo: { subject: 'Family FMEA (기본)' } });
    }

    const filtered = type === 'ALL' || type === 'LOAD'
      ? projects.filter((p: any) => p.id !== fmeaId)
      : type === 'MF'
        ? projects.filter((p: any) => {
          const pType = p.fmeaType?.toLowerCase() || (p.id.match(/pfm\d{2}-([mfp])/i)?.[1] || 'p');
          return (pType === 'm' || pType === 'f') && p.id !== fmeaId;
        })
        : projects.filter((p: any) => p.fmeaType?.toLowerCase() === type.toLowerCase() || p.id.includes(`-${type.toLowerCase()}`));

    setAvailableFmeas(filtered.map((p: any) => ({
      id: p.id,
      subject: p.fmeaInfo?.subject || p.project?.productName || '제목 없음',
      type: p.fmeaType?.toLowerCase() || (p.id.match(/pfm\d{2}-([mfp])/i)?.[1] || 'p'),
      customerName: p.fmeaInfo?.customerName || p.project?.customer || '',
      revisionNo: p.revisionNo || 'Rev.00',
      startDate: p.fmeaInfo?.fmeaStartDate || p.project?.startDate || '',
      remark: p.fmeaInfo?.remark || '',
    })));
    setFmeaSelectType(type);
    setFmeaSelectModalOpen(true);
  }, [fmeaId, setAvailableFmeas, setFmeaSelectType, setFmeaSelectModalOpen]);

  const handleFmeaSelect = useCallback(async (selectedId: string) => {
    const normalizedId = selectedId.toLowerCase();
    setFmeaSelectModalOpen(false);
    if (fmeaSelectType === 'LOAD') {
      router.push(`/dfmea/register?id=${normalizedId}`);
      window.location.reload();
    } else if (fmeaSelectType === 'MF') {
      setSelectedBaseFmea(normalizedId);
    } else {
      setSelectedBaseFmea(normalizedId);
    }
  }, [fmeaSelectType, router, setFmeaSelectModalOpen, setSelectedBaseFmea]);

  // =====================================================
  // APQP 핸들러
  // =====================================================
  const loadApqpList = useCallback(async () => {
    try {
      const res = await fetch('/api/apqp');
      const data = await res.json();
      if (data.success && data.apqps) {
        setApqpList(data.apqps.map((p: any) => ({
          apqpNo: p.apqpNo, subject: p.subject || p.productName || '', customerName: p.customerName || '',
        })));
      } else { setApqpList([]); }
    } catch (e) { console.error('[APQP 목록 로드] 오류:', e); setApqpList([]); toast.error('APQP 목록을 불러오는데 실패했습니다.'); }
  }, [setApqpList]);

  const handleApqpSelect = useCallback(async (apqpNo: string) => {
    if (!apqpNo) return;
    setSelectedParentApqp(apqpNo);
    setApqpModalOpen(false);

    // 1. ProjectLinkage에서 먼저 시도
    try {
      const res = await fetch(`/api/project-linkage?apqpNo=${apqpNo.toLowerCase()}`);
      if (res.ok) {
        const data = await res.json();
        if (data.data?.[0]) {
          const linkage = data.data[0];
          setFmeaInfo(prev => ({
            ...prev,
            companyName: linkage.companyName || prev.companyName || '',
            customerName: linkage.customerName || prev.customerName || '',
            modelYear: linkage.modelYear || prev.modelYear || '',
            subject: linkage.subject || prev.subject || '',
            engineeringLocation: linkage.engineeringLocation || prev.engineeringLocation || '',
            fmeaStartDate: linkage.startDate || prev.fmeaStartDate || '',
            fmeaRevisionDate: linkage.revisionDate || prev.fmeaRevisionDate || '',
            designResponsibility: linkage.processResponsibility || prev.designResponsibility || '',
            confidentialityLevel: linkage.confidentialityLevel || prev.confidentialityLevel || '',
            fmeaResponsibleName: linkage.responsibleName || prev.fmeaResponsibleName || '',
          }));
          return;
        }
      }
    } catch (e) { console.error('[APQP 연동정보 조회] 오류:', e); }

    // 2. APQP에서 직접 조회 (폴백)
    try {
      const apqpRes = await fetch(`/api/apqp?apqpNo=${apqpNo.toLowerCase()}`);
      if (apqpRes.ok) {
        const apqpData = await apqpRes.json();
        const apqp = apqpData.apqp || apqpData.apqps?.[0];
        if (apqp) {
          setFmeaInfo(prev => ({
            ...prev,
            companyName: apqp.companyName || prev.companyName || '',
            customerName: apqp.customerName || prev.customerName || '',
            modelYear: apqp.modelYear || prev.modelYear || '',
            subject: apqp.subject || apqp.productName || prev.subject || '',
            engineeringLocation: apqp.engineeringLocation || prev.engineeringLocation || '',
            fmeaStartDate: apqp.apqpStartDate || prev.fmeaStartDate || '',
            fmeaRevisionDate: apqp.apqpRevisionDate || prev.fmeaRevisionDate || '',
            designResponsibility: apqp.processResponsibility || prev.designResponsibility || '',
            confidentialityLevel: apqp.confidentialityLevel || prev.confidentialityLevel || '',
            fmeaResponsibleName: apqp.apqpResponsibleName || prev.fmeaResponsibleName || '',
          }));
        }
      }
    } catch (e) { console.error('[APQP 정보 조회] 오류:', e); }
  }, [setSelectedParentApqp, setApqpModalOpen, setFmeaInfo]);

  // =====================================================
  // FMEA명 검증
  // =====================================================
  const loadFmeaNameList = useCallback(async () => {
    let projects: any[] = [];
    try {
      const res = await fetch('/api/fmea/projects?type=D');
      const data = await res.json();
      if (data.success && data.projects?.length > 0) projects = data.projects;
    } catch (e) { console.error('[FMEA명 목록 조회] 오류:', e); }
    setFmeaNameList(projects.map((p: any) => ({
      id: p.id, name: p.fmeaInfo?.subject || p.project?.productName || '제목 없음', type: p.fmeaType || 'F',
    })));
  }, [setFmeaNameList]);

  const checkDuplicateName = useCallback((name: string): string | null => {
    if (!name.trim()) return null;
    const currentType = fmeaInfo.fmeaType || 'F';
    const duplicate = fmeaNameList.find(f =>
      f.name.toLowerCase() === name.toLowerCase() && f.id !== fmeaId && f.type === currentType
    );
    return duplicate ? `⚠️ "${duplicate.name}" (${duplicate.id})와 중복됩니다!` : null;
  }, [fmeaInfo.fmeaType, fmeaNameList, fmeaId]);

  const handleFmeaNameChange = useCallback((value: string) => {
    updateField('subject', value);
    if (fmeaNameList.length > 0) setDuplicateWarning(checkDuplicateName(value));
  }, [updateField, fmeaNameList, checkDuplicateName, setDuplicateWarning]);

  // =====================================================
  // 변경 이력 기록
  // =====================================================
  const recordChangeHistory = useCallback((targetId: string) => {
    if (!originalData) return;
    const fieldLabels: Record<keyof FMEAInfo, string> = {
      companyName: '회사명', engineeringLocation: '엔지니어링 위치', customerName: '고객명',
      modelYear: '모델 연식', subject: 'FMEA명', fmeaStartDate: '시작 일자',
      fmeaRevisionDate: '목표 완료일', fmeaProjectName: '프로젝트명', fmeaId: 'FMEA ID',
      fmeaType: 'FMEA 유형', designResponsibility: '공정 책임', confidentialityLevel: '기밀유지 수준',
      fmeaResponsibleName: 'FMEA 담당자', linkedCpNo: '연동 CP', linkedPfdNo: '연동 PFD', linkedDfmeaNo: '연동 DFMEA',
      partName: '부품명', partNo: '품번', createdAt: '최초 작성일', updatedAt: '수정일',
    };
    const changes: { field: string; oldValue: string; newValue: string }[] = [];
    (Object.keys(fmeaInfo) as (keyof FMEAInfo)[]).forEach(key => {
      const oldVal = originalData[key] || '';
      const newVal = fmeaInfo[key] || '';
      if (oldVal !== newVal) changes.push({ field: fieldLabels[key] || key, oldValue: oldVal, newValue: newVal });
    });
    if (changes.length === 0) return;
    const historyKey = `fmea_change_history_${targetId}`;
    const existingHistory = JSON.parse(localStorage.getItem(historyKey) || '[]');
    existingHistory.unshift({
      id: `CH-${Date.now()}`, timestamp: new Date().toISOString(), user: user?.name || 'Unknown',
      fmeaId: targetId, fmeaName: fmeaInfo.subject || '', changes,
      description: changes.map(c => `${c.field}: "${c.oldValue}" → "${c.newValue}"`).join(', '),
    });
    localStorage.setItem(historyKey, JSON.stringify(existingHistory.slice(0, 100)));
  }, [originalData, fmeaInfo, user]);

  // =====================================================
  // 저장
  // =====================================================
  const handleSave = useCallback(async () => {
    if (!fmeaId) {
      alert('PFMEA ID가 없습니다. "새로 작성" 버튼을 눌러 ID를 먼저 생성해주세요.');
      setIsCreateModalOpen(true);
      return;
    }
    if (!fmeaInfo.subject?.trim()) { alert('PFMEA명을 입력해주세요.'); return; }

    if (fmeaNameList.length === 0) await loadFmeaNameList();
    const duplicate = checkDuplicateName(fmeaInfo.subject);
    if (duplicate) {
      if (!confirm(`${duplicate}\n\n동일한 이름으로 저장하시겠습니까?`)) return;
    }

    setSaveStatus('saving');
    try {
      const finalId = fmeaId.toLowerCase();
      const updatedFmeaInfo = {
        ...fmeaInfo,
        linkedCpNo: linkedCpList.length > 0 ? linkedCpList[0].id : (fmeaInfo.linkedCpNo || ''),
        linkedPfdNo: linkedPfdList.length > 0 ? linkedPfdList[0].id : (fmeaInfo.linkedPfdNo || ''),
      };

      const res = await fetch('/api/fmea/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fmeaId: finalId, fmeaType: updatedFmeaInfo.fmeaType,
          project: { projectName: updatedFmeaInfo.subject, customer: updatedFmeaInfo.customerName, productName: updatedFmeaInfo.subject },
          fmeaInfo: { ...updatedFmeaInfo, fmeaId: finalId },
          cftMembers: cftMembers.filter(m => m.name?.trim()),
          parentApqpNo: selectedParentApqp, parentFmeaId: selectedBaseFmea,
          ...(revParam ? { revisionNo: revParam } : {}),
        }),
      });

      const result = await res.json();
      if (!result.success && !result.dbError) throw new Error(result.error || result.message);
      if (result.dbSaved === false) {
        alert('⚠️ DB 연결 실패로 로컬에만 저장되었습니다.\n네트워크 상태를 확인해주세요.');
      }

      if (originalData) recordChangeHistory(finalId);

      syncToLocalStorage(finalId, fmeaInfo, cftMembers, selectedBaseFmea, selectedParentApqp);
      localStorage.setItem('dfmea-last-edited', finalId);
      setOriginalData({ ...fmeaInfo });

      // ProjectLinkage 동기화
      try {
        await fetch('/api/project-linkage', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            dfmeaId: finalId, apqpNo: selectedParentApqp || null,
            cpNo: fmeaInfo.linkedCpNo || null, pfdNo: fmeaInfo.linkedPfdNo || null,
            linkedDfmeaNo: fmeaInfo.linkedDfmeaNo || null,
            projectName: fmeaInfo.subject || '', subject: fmeaInfo.subject || '',
            companyName: fmeaInfo.companyName || '', customerName: fmeaInfo.customerName || '',
            responsibleName: fmeaInfo.fmeaResponsibleName || '', modelYear: fmeaInfo.modelYear || '',
            engineeringLocation: fmeaInfo.engineeringLocation || '',
            processResponsibility: fmeaInfo.designResponsibility || '',
            confidentialityLevel: fmeaInfo.confidentialityLevel || '',
            partName: fmeaInfo.partName || fmeaInfo.subject || '', partNo: fmeaInfo.partNo || '',
          }),
        });
      } catch (linkErr) { console.error('[ProjectLinkage 동기화] 오류:', linkErr); }

      // ✅ 접속로그: 기초정보 저장 + 변경 필드 상세
      const changedFields: string[] = [];
      if (originalData) {
        const fieldLabels: Partial<Record<keyof FMEAInfo, string>> = {
          subject: 'FMEA명', customerName: '고객명', companyName: '회사명',
          fmeaResponsibleName: 'FMEA담당자', designResponsibility: '공정책임',
          engineeringLocation: '엔지니어링위치', modelYear: '모델연식',
          partName: '품명', partNo: '품번', confidentialityLevel: '기밀수준',
          fmeaStartDate: '시작일', fmeaRevisionDate: '목표완료일',
        };
        (Object.keys(fieldLabels) as (keyof FMEAInfo)[]).forEach(key => {
          if ((originalData[key] || '') !== (fmeaInfo[key] || '')) changedFields.push(fieldLabels[key]!);
        });
      }
      const desc = isEditMode
        ? `PFMEA 수정: ${fmeaInfo.subject}${changedFields.length > 0 ? ` (${changedFields.join(', ')})` : ''}`
        : `DFMEA 등록: ${fmeaInfo.subject}`;
      await recordAccessLog(isEditMode ? '수정' : '추가', '기초정보', desc, finalId);

      // ✅ 접속로그: CFT 멤버 저장
      const filledMembers = cftMembers.filter(m => m.name?.trim());
      if (filledMembers.length > 0) {
        await recordAccessLog('수정', 'CFT', `CFT ${filledMembers.length}명 저장: ${filledMembers.map(m => `${m.role}(${m.name})`).join(', ')}`, finalId);
      }

      setSaveStatus('saved');
      if (!isEditMode) router.replace(`/dfmea/register?id=${finalId}`);

      // ★ 개정 모드: 저장 후 기초정보 확인 화면 표시 (수정/사용 선택)
      if (isRevisionMode) {
        setTimeout(() => { setSaveStatus('idle'); setShowMasterReview(true); }, 1000);
      } else {
        setTimeout(() => setSaveStatus('idle'), 2000);
      }
    } catch (e: any) {
      alert('저장 실패: ' + (e.message || '알 수 없는 오류'));
      setSaveStatus('idle');
    }
  }, [fmeaId, fmeaInfo, cftMembers, isEditMode, isRevisionMode, selectedBaseFmea, selectedParentApqp,
    linkedCpList, linkedPfdList, fmeaNameList, originalData, revParam,
    setSaveStatus, setOriginalData, setIsCreateModalOpen, setShowMasterReview,
    loadFmeaNameList, checkDuplicateName, recordChangeHistory, recordAccessLog, router]);

  // =====================================================
  // 기타 핸들러
  // =====================================================
  const handleNewRegister = useCallback(() => { setIsCreateModalOpen(true); }, [setIsCreateModalOpen]);

  const handleUserSelect = useCallback((selectedUser: UserInfo) => {
    if (userModalTarget === 'responsible' || userModalTarget === 'design') {
      // ✅ FMEA담당자 선택 → fmeaInfo 업데이트
      setFmeaInfo(prev => ({
        ...prev,
        fmeaResponsibleName: selectedUser.name,
        designResponsibility: selectedUser.department || prev.designResponsibility || '',
        companyName: 'AMPSYSTEM',
        engineeringLocation: (selectedUser as any).factory || prev.engineeringLocation || '',
      }));
      // ✅ CFT Leader도 자동 동기화 (FMEA담당자 = CFT Leader)
      setCftMembers(prev => prev.map(m =>
        m.role === 'Leader' ? {
          ...m,
          name: selectedUser.name,
          department: selectedUser.department || m.department || '',
          position: selectedUser.position || m.position || '',
          phone: selectedUser.phone || m.phone || '',
          email: selectedUser.email || m.email || '',
        } : m
      ));
    } else if (core.selectedMemberIndex !== null) {
      const updated = [...cftMembers];
      const targetMember = updated[core.selectedMemberIndex];
      updated[core.selectedMemberIndex] = {
        ...targetMember,
        name: selectedUser.name, department: selectedUser.department || '',
        position: selectedUser.position || '', phone: selectedUser.phone || '', email: selectedUser.email || '',
        task: selectedUser.remark || targetMember.task || '',
      };
      setCftMembers(updated);
      // ✅ CFT Leader 변경 → fmeaResponsibleName 자동 동기화
      if (targetMember.role === 'Leader') {
        setFmeaInfo(prev => ({
          ...prev,
          fmeaResponsibleName: selectedUser.name,
          designResponsibility: selectedUser.department || prev.designResponsibility || '',
        }));
      }
    }
    // ✅ 접속로그: 사용자 선택 기록
    const targetLabel = userModalTarget === 'responsible' ? 'FMEA담당자' : userModalTarget === 'design' ? '공정책임' : `CFT(${cftMembers[core.selectedMemberIndex ?? 0]?.role || ''})`;
    recordAccessLog('수정', targetLabel, `${targetLabel} 지정: ${selectedUser.name}(${selectedUser.position || ''})`, fmeaId || editId || '');

    setUserModalOpen(false);
  }, [userModalTarget, cftMembers, setCftMembers, setFmeaInfo, setUserModalOpen, core.selectedMemberIndex, recordAccessLog, fmeaId, editId]);

  return {
    updateField, handlePartNameChange,
    handleAddLinkedDoc, handleRemoveLinkedDoc, handleToggleLinkage,
    openFmeaSelectModal, handleFmeaSelect,
    loadApqpList, handleApqpSelect,
    loadFmeaNameList, checkDuplicateName, handleFmeaNameChange,
    recordChangeHistory,
    handleSave, handleNewRegister, handleUserSelect,
    cftAlertRoles, setCftAlertRoles,
  };
}
