/**
 * @file useRecommendHandlers.ts
 * @description AllTabEmpty에서 추출한 추천/개선 핸들러
 * - handleAPImprove: AP 최단거리 개선
 * - handleRecommendImprovement: 산업DB 기반 개선추천 (모달)
 * - autoRecommendO: 발생도(O) 자동추천
 */

import { useCallback, useState } from 'react';
import type { WorksheetState } from '../../../constants';
import type { ProcessedFMGroup } from '../processFailureLinks';
import type { RecommendCandidate } from '../RecommendImprovementModal';
import { applyAPImprovement } from './apMinCostMap';
import { calcAP, getMaxSeverity, getSafeSODValue } from '../riskOptUtils';
import { getAllPaths } from '../APImproveModal';
import { correctOccurrence } from './pcOccurrenceMap';
import { recommendDetection } from './detectionRatingMap';
import { autoFillMissingOccurrence } from '../../../utils/autoFillOccurrence';

interface ScoredPC { method: string; o: number | null }
interface ScoredDC { method: string; d: number }

interface UseRecommendHandlersParams {
  state: WorksheetState | undefined;
  setState: React.Dispatch<React.SetStateAction<WorksheetState>> | undefined;
  setDirty: React.Dispatch<React.SetStateAction<boolean>> | undefined;
  saveAtomicDB?: (force?: boolean) => void | Promise<void>;
  processedFMGroups: ProcessedFMGroup[];
  globalMaxSeverity: number;
}

/** 모달 상태 */
export interface RecommendModalState {
  isOpen: boolean;
  candidates: RecommendCandidate[];
  cftLeaderName: string;
}

/** 자동생성값 판별 (덮어쓰기 가능): 빈값, "-", "N/A", "[추천]..." */
function isAutoGenerated(val: string): boolean {
  const v = (val || '').trim();
  return !v || v === '-' || v === 'N/A' || v.startsWith('[추천]');
}

// ─── 3단계 폴백 헬퍼 ───

function findBestPC(scoredPCs: ScoredPC[], targetO: number): { method: string; achievedO: number } | null {
  if (scoredPCs.length === 0) return null;
  let bestTarget: ScoredPC | null = null;
  let bestAny: ScoredPC | null = null;
  for (const c of scoredPCs) {
    if (c.o !== null && c.o > 0) {
      if (c.o <= targetO && (!bestTarget || c.o < (bestTarget.o ?? 99))) bestTarget = c;
      if (!bestAny || c.o < (bestAny.o ?? 99)) bestAny = c;
    }
  }
  if (bestTarget) return { method: bestTarget.method, achievedO: bestTarget.o! };
  if (bestAny) return { method: bestAny.method, achievedO: bestAny.o! };
  return { method: scoredPCs[0].method, achievedO: targetO };
}

function findBestDC(scoredDCs: ScoredDC[], targetD: number): { method: string; achievedD: number } | null {
  if (scoredDCs.length === 0) return null;
  let bestTarget: ScoredDC | null = null;
  let bestAny: ScoredDC | null = null;
  for (const c of scoredDCs) {
    if (c.d > 0) {
      if (c.d <= targetD && (!bestTarget || c.d < bestTarget.d)) bestTarget = c;
      if (!bestAny || c.d < bestAny.d) bestAny = c;
    }
  }
  if (bestTarget) return { method: bestTarget.method, achievedD: bestTarget.d };
  if (bestAny) return { method: bestAny.method, achievedD: bestAny.d };
  return { method: scoredDCs[0].method, achievedD: targetD };
}

export function useRecommendHandlers({
  state, setState, setDirty, saveAtomicDB,
  processedFMGroups, globalMaxSeverity,
}: UseRecommendHandlersParams) {

  // ★ 개선추천 모달 상태
  const [recommendModal, setRecommendModal] = useState<RecommendModalState>({
    isOpen: false, candidates: [], cftLeaderName: '',
  });

  // ★ AP 최단거리 개선 핸들러
  const handleAPImprove = useCallback((targetLevel: 'L' | 'M') => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};

    const uniqueKeys: string[] = [];
    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (row.fcId && fmGroup.fmId) {
          uniqueKeys.push(`${fmGroup.fmId}-${row.fcId}`);
        }
      });
    });

    const { updatedData, stats } = applyAPImprovement(
      riskData, uniqueKeys, globalMaxSeverity, targetLevel,
    );

    if (stats.improved === 0 && stats.unreachable === 0) {
      alert(`개선 대상 없음: 모든 항목이 이미 ${targetLevel === 'L' ? 'L' : 'M 이하'} 등급입니다.`);
      return;
    }

    setState(prev => ({ ...prev, riskData: updatedData as Record<string, string | number> }));
    setDirty?.(true);

    const lines = [
      `[AP 최단거리 개선 완료]`,
      `S(심각도): ${globalMaxSeverity} (고정)`,
      `대상: ${stats.total}건`,
      `개선: ${stats.improved}건`,
    ];
    if (stats.hToL > 0) lines.push(`  H→L: ${stats.hToL}건`);
    if (stats.hToM > 0) lines.push(`  H→M: ${stats.hToM}건`);
    if (stats.mToL > 0) lines.push(`  M→L: ${stats.mToL}건`);
    if (stats.unreachable > 0) lines.push(`개선불가(O=2,D=2에서도 L 미달): ${stats.unreachable}건`);
    lines.push('', '※ O, D 값이 최소 cost로 자동보정되었습니다.');
    lines.push('※ 저장 버튼을 눌러 DB에 반영하세요.');
    alert(lines.join('\n'));
  }, [state, setState, setDirty, processedFMGroups, globalMaxSeverity]);

  // ★ 개선추천 — 모달 열기 (데이터 준비 + 모달 표시)
  const handleRecommendImprovement = useCallback(async () => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};

    // CFT 리더(FMEA 책임자) 이름 가져오기
    let cftLeaderName = '';
    try {
      const fmeaId = state?.fmeaId || new URLSearchParams(window.location.search).get('id') || '';
      if (fmeaId) {
        const infoRes = await fetch(`/api/fmea/info?fmeaId=${encodeURIComponent(fmeaId)}`);
        const infoData = await infoRes.json();
        cftLeaderName = infoData?.fmeaInfo?.responsible || infoData?.fmeaInfo?.fmeaResponsibleName || '';
      }
    } catch (err) { console.error('[Recommend] CFT 리더 조회 실패:', err); }

    // 산업DB에서 예방관리·검출관리 후보 가져오기 + O/D 스코어 사전 계산
    let scoredPCs: ScoredPC[] = [];
    let scoredDCs: ScoredDC[] = [];
    try {
      const [krPcRes, krDcRes] = await Promise.all([
        fetch('/api/kr-industry?type=prevention').then(r => r.json()).catch(() => ({ prevention: [] })),
        fetch('/api/kr-industry?type=detection').then(r => r.json()).catch(() => ({ detection: [] })),
      ]);
      scoredPCs = ((krPcRes.prevention || []) as { method: string }[])
        .filter(e => e.method)
        .map(e => ({ method: e.method, o: correctOccurrence(e.method).correctedO }));
      scoredDCs = ((krDcRes.detection || []) as { method: string; methodType?: string }[])
        .filter(e => e.method)
        .map(e => ({ method: e.method, d: recommendDetection(e.method) }));
    } catch (err) { console.error('[Recommend] 산업DB 조회 실패:', err); }

    // H/M 항목 수집 + 추천안 사전 계산
    const candidates: RecommendCandidate[] = [];

    processedFMGroups.forEach(fmGroup => {
      fmGroup.rows.forEach(row => {
        if (!row.fcId || !fmGroup.fmId) return;
        const uk = `${fmGroup.fmId}-${row.fcId}`;
        const s = getSafeSODValue(riskData, `risk-${uk}-S`) || getMaxSeverity(fmGroup.fmId, state);
        const o = getSafeSODValue(riskData, `risk-${uk}-O`);
        const d = getSafeSODValue(riskData, `risk-${uk}-D`);
        if (s <= 0 || o <= 0 || d <= 0) return;
        const ap = calcAP(s, o, d);
        if (ap !== 'H' && ap !== 'M') return;

        const prevKey = `prevention-opt-${uk}`;
        const detKey = `detection-opt-${uk}`;
        const curPrev = ((riskData[prevKey] as string) || '').trim();
        const curDet = ((riskData[detKey] as string) || '').trim();
        const hasPrev = !isAutoGenerated(curPrev);
        const hasDet = !isAutoGenerated(curDet);

        // 추천안 사전 계산 — ★ 단일 지표 개선 우선 (O_ONLY > D_ONLY > BOTH)
        const paths = getAllPaths(s, o, d);
        // ★ 경로 우선순위: 예방만으로 L 도달 가능하면 O_ONLY 우선 → 검출 N/A
        const effectiveRec = paths.oOnly.feasible ? 'O_ONLY' as const
          : paths.dOnly.feasible ? 'D_ONLY' as const
          : paths.both.feasible ? 'BOTH' as const
          : undefined;
        let prevRecommend = '';
        let detRecommend = '';

        if (effectiveRec) {
          const pathData = effectiveRec === 'O_ONLY' ? paths.oOnly : effectiveRec === 'D_ONLY' ? paths.dOnly : paths.both;
          const needsO = effectiveRec === 'O_ONLY' || effectiveRec === 'BOTH';
          const needsD = effectiveRec === 'D_ONLY' || effectiveRec === 'BOTH';

          if (!hasPrev && needsO) {
            const best = findBestPC(scoredPCs, pathData.targetO);
            prevRecommend = best
              ? `[추천] 발생도 ${o}→${pathData.targetO} ${best.method}`
              : `[추천] 발생도 ${o}→${pathData.targetO} 개선 필요`;
          } else if (!hasPrev && !needsO) {
            prevRecommend = 'N/A';
          }

          if (!hasDet && needsD) {
            const best = findBestDC(scoredDCs, pathData.targetD);
            detRecommend = best
              ? `[추천] 검출도 ${d}→${pathData.targetD} ${best.method}`
              : `[추천] 검출도 ${d}→${pathData.targetD} 개선 필요`;
          } else if (!hasDet && !needsD) {
            detRecommend = 'N/A';
          }
        }

        candidates.push({
          uniqueKey: uk,
          fmId: fmGroup.fmId,
          fcId: row.fcId,
          processNo: fmGroup.fmProcessNo,
          processName: fmGroup.fmProcessName,
          fmText: fmGroup.fmText,
          fcText: row.fcText,
          s, o, d, ap,
          hasPrev, hasDet,
          prevRecommend, detRecommend,
        });
      });
    });

    // 모달 열기
    setRecommendModal({ isOpen: true, candidates, cftLeaderName });
  }, [state, setState, processedFMGroups]);

  // ★ 전체적용 핸들러 (모달에서 호출)
  const applyRecommendations = useCallback((options: { prevention: boolean; detection: boolean }) => {
    if (!state || !setState) return;
    const riskData = state.riskData || {};
    const { candidates, cftLeaderName } = recommendModal;
    const updates: Record<string, string> = {};
    let count = 0;

    candidates.forEach(c => {
      const uk = c.uniqueKey;
      const prevKey = `prevention-opt-${uk}`;
      const detKey = `detection-opt-${uk}`;
      const personKey = `person-opt-${uk}`;

      if (options.prevention && !c.hasPrev && c.prevRecommend && c.prevRecommend !== 'N/A') {
        updates[prevKey] = c.prevRecommend;
      }
      if (options.detection && !c.hasDet && c.detRecommend && c.detRecommend !== 'N/A') {
        updates[detKey] = c.detRecommend;
      }

      // ★ N/A 마커 (결과 기반): 한쪽에만 추천 적용 → 반대쪽이 자동생성값이면 N/A 표시
      const wroteRealPrev = !!updates[prevKey] && updates[prevKey] !== 'N/A';
      const wroteRealDet = !!updates[detKey] && updates[detKey] !== 'N/A';
      if (wroteRealPrev && !wroteRealDet && !c.hasDet && isAutoGenerated((riskData[detKey] as string) || '')) {
        updates[detKey] = 'N/A';
      }
      if (wroteRealDet && !wroteRealPrev && !c.hasPrev && isAutoGenerated((riskData[prevKey] as string) || '')) {
        updates[prevKey] = 'N/A';
      }

      // 책임자 자동 배정
      if (cftLeaderName && (updates[prevKey] || updates[detKey])) {
        if (!((riskData[personKey] as string) || '').trim()) {
          updates[personKey] = cftLeaderName;
        }
      }

      if (updates[prevKey] || updates[detKey]) count++;
    });

    if (Object.keys(updates).length === 0) return;

    setState(prev => ({ ...prev, riskData: { ...(prev.riskData || {}), ...updates } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [state, setState, setDirty, saveAtomicDB, recommendModal]);

  // ★ 개별 항목 적용 핸들러 (IndustryImproveModal에서 호출)
  const applySingleRecommendation = useCallback((
    uniqueKey: string, mode: 'prevention' | 'detection', value: string,
  ) => {
    if (!setState) return;
    const key = mode === 'prevention' ? `prevention-opt-${uniqueKey}` : `detection-opt-${uniqueKey}`;
    setState(prev => ({
      ...prev,
      riskData: { ...(prev.riskData || {}), [key]: value },
    }));
    setDirty?.(true);
    saveAtomicDB?.(true);
  }, [setState, setDirty, saveAtomicDB]);

  // ★ 모달 닫기
  const closeRecommendModal = useCallback(() => {
    setRecommendModal(prev => ({ ...prev, isOpen: false }));
  }, []);

  // ★ 발생도(O) 자동추천 — PC 텍스트 기반
  const autoRecommendO = useCallback(() => {
    if (!state?.riskData || !setState) return;
    const fls = (state.failureLinks || []).map((fl) => ({
      fmId: String(fl.fmId || ''),
      fcId: String(fl.fcId || ''),
    }));
    const result = autoFillMissingOccurrence(state.riskData || {}, fls);
    if (result.filledCount === 0) {
      alert('발생도(O) 누락이 없습니다.');
      return;
    }
    setState((prev: WorksheetState) => ({ ...prev, riskData: result.updatedRiskData as { [key: string]: string | number } }));
    setDirty?.(true);
    saveAtomicDB?.(true);
    alert(`발생도(O) ${result.filledCount}건 자동추천 완료\n\n${result.details.slice(0, 5).map(d => `• ${d.reason}`).join('\n')}${result.details.length > 5 ? `\n... 외 ${result.details.length - 5}건` : ''}`);
  }, [state?.riskData, state?.failureLinks, setState, setDirty, saveAtomicDB]);

  return {
    handleAPImprove,
    handleRecommendImprovement,
    autoRecommendO,
    // ★ 모달 관련
    recommendModal,
    closeRecommendModal,
    applyRecommendations,
    applySingleRecommendation,
  };
}
