/**
 * PROJECT DASHBOARD 샘플 데이터
 *
 * LBS 세미콘 AU BUMP 프로젝트 데이터
 * 🔥 날짜 표기: YY/MM/DD (전역 표준)
 */

import { ProjectDashboardData } from '../types/project-dashboard';

export const SAMPLE_PROJECTS: ProjectDashboardData[] = [
  {
    projectId: 'P/T-2026-0001',
    createdAt: '26/01/10',
    projectName: 'AU BUMP MASTER PFMEA',
    customer: 'Qualcomm',
    factory: '평택공장',
    modelYear: '2026',
    program: 'AU BUMP 12inch',
    startDate: '26/01/01',
    endDate: '26/12/31',
    duration: 365,
    progress: 85,
    pfdStatus: 'Complete',
    fmeaStatus: 'Progress',
    cpStatus: 'Progress',
    wsStatus: 'Open',
    pmStatus: 'Open',
    overallStatus: 'Progress',
    scheduleCompliance: 92,
    delayedTasks: 1
  },
  {
    projectId: 'P/T-2026-0002',
    createdAt: '26/02/01',
    projectName: 'Cu Pillar Bump 개발',
    customer: 'Qualcomm',
    factory: '평택공장',
    modelYear: '2026',
    program: 'Cu Pillar 8inch',
    startDate: '26/02/01',
    endDate: '26/11/30',
    duration: 303,
    progress: 72,
    pfdStatus: 'Complete',
    fmeaStatus: 'Progress',
    cpStatus: 'Open',
    wsStatus: 'Open',
    pmStatus: 'Open',
    overallStatus: 'Progress',
    scheduleCompliance: 85,
    delayedTasks: 2
  },
  {
    projectId: 'P/T-2026-0003',
    createdAt: '26/02/15',
    projectName: 'Solder Bump 양산',
    customer: 'Qualcomm',
    factory: '평택공장',
    modelYear: '2026',
    program: 'Solder Bump 12inch',
    startDate: '26/03/01',
    endDate: '26/12/31',
    duration: 306,
    progress: 45,
    pfdStatus: 'Progress',
    fmeaStatus: 'Open',
    cpStatus: 'Open',
    wsStatus: 'Open',
    pmStatus: 'Open',
    overallStatus: 'Progress',
    scheduleCompliance: 75,
    delayedTasks: 3
  },
  {
    projectId: 'P/T-2026-0004',
    createdAt: '26/03/01',
    projectName: 'RDL 공정 개선',
    customer: 'Qualcomm',
    factory: '평택공장',
    modelYear: '2026',
    program: 'RDL 12inch',
    startDate: '26/04/01',
    endDate: '26/12/31',
    duration: 275,
    progress: 30,
    pfdStatus: 'Open',
    fmeaStatus: 'Open',
    cpStatus: 'Open',
    wsStatus: 'Open',
    pmStatus: 'Open',
    overallStatus: 'Open',
    scheduleCompliance: 65,
    delayedTasks: 4
  },
  {
    projectId: 'P/T-2026-0005',
    createdAt: '26/03/10',
    projectName: 'Wafer Level CSP',
    customer: 'Qualcomm',
    factory: '평택공장',
    modelYear: '2026',
    program: 'WLCSP 8inch',
    startDate: '26/04/01',
    endDate: '27/03/31',
    duration: 365,
    progress: 20,
    pfdStatus: 'Open',
    fmeaStatus: 'Open',
    cpStatus: 'Open',
    wsStatus: 'Open',
    pmStatus: 'Open',
    overallStatus: 'Open',
    scheduleCompliance: 55,
    delayedTasks: 5
  },
];
