/**
 * @file index.ts
 * @description STEP B 전처리 오케스트레이터 (DEPRECATED — 위치기반 position-parser로 전환)
 *
 * 레거시 import-builder, sample-data-loader, uuid-generator 제거됨 (2026-03-22)
 * 이 파일은 기존 2시트/단일시트 파서 호환용으로 유지. 새 Import는 position-parser 사용.
 */

import { WarningCollector } from './types';
import type { StepBConvertResult } from './types';
import {
  runParsingCriteriaValidation,
  type ParseValidationReport,
} from '../utils/parsing-criteria-validator';

export interface StepBConvertResultWithValidation extends StepBConvertResult {
  parsingValidation?: ParseValidationReport;
}

/**
 * @deprecated 위치기반 5시트 Import는 position-parser를 사용하세요.
 * 이 함수는 레거시 2시트/단일시트 호환용으로만 유지됩니다.
 */
export async function parseStepBWorkbook(_file: File): Promise<StepBConvertResultWithValidation> {
  const warn = new WarningCollector();
  warn.error('DEPRECATED', '이 파서는 deprecated입니다. 위치기반 5시트 포맷(L1/L2/L3/FC)을 사용하세요.');

  return {
    flatData: [],
    failureChains: [],
    warnings: warn.getAll(),
    statistics: {
      totalRows: 0, processCount: 0, fmCount: 0,
      fcCount: 0, feCount: 0, dcCount: 0, pcCount: 0,
      chainCount: 0, autoGeneratedCount: 0,
    },
  };
}

// Re-exports
export type { StepBConvertResult, StepBWarning, StepBMasterChain, StepBStatistics } from './types';
export { WarningCollector } from './types';
export type { ParseValidationReport } from '../utils/parsing-criteria-validator';
