/**
 * @file index.ts
 * @description STEP B 전처리 오케스트레이터
 * 엑셀 파일 → 헤더 감지 → 행 파싱 → Import 데이터 빌드 → 검증 → 결과 반환
 * @created 2026-03-05
 */

import ExcelJS from 'exceljs';
import { WarningCollector } from './types';
import type { StepBConvertResult } from './types';
import { detectStepBColumns } from './header-detector';
import { parseStepBRows } from './row-parser';
import { buildImportData, convertToImportFormat } from './import-builder';
import { validateStepBResult, computeStatistics } from './validator';
import { fetchSampleData } from '@/lib/sample-data-loader';
import {
  runParsingCriteriaValidation,
  type ParseValidationReport,
} from '../utils/parsing-criteria-validator';

export interface StepBConvertResultWithValidation extends StepBConvertResult {
  parsingValidation?: ParseValidationReport;
}

/**
 * STEP B .xlsx 파일을 Smart FMEA Import 형식으로 변환
 *
 * 파이프라인:
 * 1. ExcelJS로 워크북 로드 (ArrayBuffer)
 * 2. detectStepBColumns() → 헤더 자동 감지
 * 3. parseStepBRows() → 행 파싱 (carry-forward + 정규화)
 * 4. buildImportData() → 구조화된 Import 데이터 빌드
 * 5. convertToImportFormat() → ImportedFlatData[] + MasterFailureChain[]
 * 6. validateStepBResult() → 교차 검증
 * 7. runParsingCriteriaValidation() → 파싱 기준표 검증 + 자동수정
 *
 * @param file File 객체 (.xlsx)
 * @returns StepBConvertResultWithValidation
 */
export async function parseStepBWorkbook(file: File): Promise<StepBConvertResultWithValidation> {
  const warn = new WarningCollector();

  // 1. ExcelJS 워크북 로드
  const arrayBuffer = await file.arrayBuffer();
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(arrayBuffer);

  const worksheet = workbook.worksheets[0];
  if (!worksheet) {
    warn.error('NO_SHEET', '워크시트가 없습니다.');
    return {
      flatData: [],
      failureChains: [],
      warnings: warn.getAll(),
      statistics: {
        totalRows: 0, processCount: 0, fmCount: 0,
        fcCount: 0, feCount: 0, dcCount: 0, pcCount: 0,
        chainCount: 0, autoGeneratedCount: 0,
      },
    };
  }

  // 2. 헤더 자동 감지
  const { colMap, headerRow } = detectStepBColumns(worksheet, warn);

  // 3. 행 파싱
  const parsedRows = parseStepBRows(worksheet, colMap, headerRow, warn);

  if (parsedRows.length === 0) {
    warn.error('NO_DATA', '파싱된 데이터가 없습니다. 엑셀 형식을 확인해주세요.');
    return {
      flatData: [],
      failureChains: [],
      warnings: warn.getAll(),
      statistics: {
        totalRows: 0, processCount: 0, fmCount: 0,
        fcCount: 0, feCount: 0, dcCount: 0, pcCount: 0,
        chainCount: 0, autoGeneratedCount: 0,
      },
    };
  }

  // 4. Import 데이터 빌드 — m066 골든 레퍼런스 사전 로드
  const sampleData = await fetchSampleData();
  const buildData = buildImportData(parsedRows, warn, sampleData);

  // 5. ImportedFlatData[] + MasterFailureChain[] 변환
  const { flatData, failureChains } = convertToImportFormat(buildData, warn);

  // 6. 교차 검증 (기존 V1~V4)
  validateStepBResult(buildData, warn);

  // 7. ★ 파싱 기준표 검증 + 자동수정 + 피드백
  const parsingValidation = runParsingCriteriaValidation(flatData, failureChains);

  // 자동수정으로 추가된 항목이 있으면 warn에 기록
  if (parsingValidation.autoFixes.length > 0) {
    for (const fix of parsingValidation.autoFixes) {
      warn.warn('AUTOFIX', `[${fix.ruleId}] ${fix.description}`);
    }
  }
  if (parsingValidation.failCount > 0) {
    warn.error('CRITERIA_FAIL', `파싱 기준표 FAIL ${parsingValidation.failCount}건 → ${parsingValidation.summary}`);
  }

  // 8. 통계 계산
  const autoGeneratedCount = flatData.filter(d => d.inherited).length;
  const statistics = computeStatistics(buildData, autoGeneratedCount);

  return {
    flatData,
    failureChains,
    warnings: warn.getAll(),
    statistics,
    parsingValidation,
  };
}

// Re-exports
export type { StepBConvertResult, StepBWarning, StepBMasterChain, StepBStatistics } from './types';
export { WarningCollector } from './types';
export type { ParseValidationReport } from '../utils/parsing-criteria-validator';