/**
 * @file validator.ts
 * @description STEP B 변환 결과 교차 검증 (V1~V4)
 * Python validate() 포팅
 * @created 2026-03-05
 */

import type { StepBBuildData, StepBStatistics, WarningCollector } from './types';

export interface ValidationResult {
  v1: { c4Count: number; fcFeCount: number; ok: boolean };
  v2: { a5Count: number; fcFmCount: number; ok: boolean };
  v3: { b4Count: number; fcFcCount: number; ok: boolean };
  v4: { duplicateCount: number; ok: boolean };
}

/**
 * 빌드 데이터 교차 검증
 *
 * V1: C4 FE 수 = FC 고유 FE 수
 * V2: A5 FM 수 = FC 고유 FM 수
 * V3: B4 FC 수 = FC 고유 FC 수
 * V4: B2 MC/MN 동일기능 중복 감지
 */
export function validateStepBResult(
  data: StepBBuildData,
  warn: WarningCollector,
): ValidationResult {
  const chains = data.fcChains;

  // V1: C4 고유 FE = FC 고유 FE (scope 무관하게 FE 텍스트 기준)
  // C4는 scope|fe 키로 저장되므로 같은 FE가 YP+SP에 모두 있으면 2건
  // 비교 시에는 scope 제외한 순수 FE 고유 값으로 비교해야 함
  const c4FeSet = new Set(data.c4.map(c => c.fe));
  const c4FeCount = c4FeSet.size;
  const fcFeSet = new Set(chains.map(c => c.fe));
  const fcFeCount = fcFeSet.size;
  const v1Ok = c4FeCount === fcFeCount;
  if (data.c4.length === 0) {
    warn.error('V1_FE_ZERO', '고장영향(FE)이 0건입니다! 엑셀의 FE 컬럼 헤더명을 확인해주세요. (지원: 고장영향, 고장의 영향, 영향(FE))');
  }
  warn.info('V1_FE', `C4 고장영향 ${data.c4.length}건(FE고유 ${c4FeCount}) / FC시트 FE고유 ${fcFeCount}건 ${v1Ok ? '✅' : '⚠️ 불일치'}`);

  // V2: A5 FM = FC FM 고유
  let a5Count = 0;
  for (const fms of data.a5.values()) a5Count += fms.length;
  const fcFmSet = new Set(chains.map(c => `${c.procNo}|${c.fm}`));
  const fcFmCount = fcFmSet.size;
  const v2Ok = a5Count === fcFmCount;
  warn.info('V2_FM', `A5 고장형태 ${a5Count}건 / FC시트 FM고유 ${fcFmCount}건 ${v2Ok ? '✅' : '⚠️ 불일치'}`);

  // V3: B4 FC = FC FC 고유
  let b4Count = 0;
  for (const fcs of data.b4.values()) b4Count += fcs.length;
  const fcFcSet = new Set(chains.map(c => `${c.procNo}|${c.m4}|${c.fc}`));
  const fcFcCount = fcFcSet.size;
  // ★ MEDIUM-4: B4=0 AND FC=0 동시 통과 차단 — 빈 FMEA 감지
  const v3Ok = b4Count === fcFcCount && !(b4Count === 0 && fcFcCount === 0);
  if (b4Count === 0 && fcFcCount === 0) {
    warn.error('V3_EMPTY', 'B4(고장원인)과 FC 모두 0건 — 빈 FMEA입니다. 엑셀 데이터를 확인해주세요.');
  }
  warn.info('V3_FC', `B4 고장원인 ${b4Count}건 / FC시트 FC고유 ${fcFcCount}건 ${v3Ok ? '✅' : '⚠️ 불일치'}`);

  // V4: B2 MC/MN 동일기능 중복
  const b2FuncMap = new Map<string, string[]>();
  for (const [pno, items] of data.b2) {
    for (const item of items) {
      const key = `${pno}|${item.func}`;
      const m4List = b2FuncMap.get(key) || [];
      m4List.push(item.m4);
      b2FuncMap.set(key, m4List);
    }
  }
  let dupCount = 0;
  for (const [key, m4s] of b2FuncMap) {
    const uniqueM4s = new Set(m4s);
    if (uniqueM4s.size > 1) {
      dupCount++;
      if (dupCount <= 3) {
        const [pno, func] = key.split('|');
        warn.warn('B2_DUP', `공정${pno} B2 중복: '${func.substring(0, 30)}'`, undefined, `[${[...uniqueM4s].join(',')}]`);
      }
    }
  }
  const v4Ok = dupCount === 0;
  warn.info('V4_B2', `B2 MC/MN 동일기능 중복: ${v4Ok ? '✅' : `⚠️ ${dupCount}건`}`);

  return {
    v1: { c4Count: c4FeCount, fcFeCount, ok: v1Ok },
    v2: { a5Count, fcFmCount, ok: v2Ok },
    v3: { b4Count, fcFcCount, ok: v3Ok },
    v4: { duplicateCount: dupCount, ok: v4Ok },
  };
}

/**
 * 통계 정보 계산
 */
export function computeStatistics(data: StepBBuildData, autoGeneratedCount: number): StepBStatistics {
  let fmCount = 0;
  for (const fms of data.a5.values()) fmCount += fms.length;

  let fcCount = 0;
  for (const fcs of data.b4.values()) fcCount += fcs.length;

  let dcCount = 0;
  for (const dcs of data.a6.values()) dcCount += dcs.length;

  let pcCount = 0;
  for (const pcs of data.b5.values()) pcCount += pcs.length;

  return {
    totalRows: data.fcChains.length,
    processCount: data.procMaster.size,
    fmCount,
    fcCount,
    feCount: data.c4.length,
    dcCount,
    pcCount,
    chainCount: data.fcChains.length,
    autoGeneratedCount,
  };
}
